//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCAppDelSnapSaver.h"

@implementation SCAppDelSnapSaver

+ (void)handleSnapSaveCompletion:(_Bool)arg1 {
	if (arg1) {
		[ProgressHUD showSuccess:[[SCAppDelPrefs sharedInstance] localizedStringForKey:@"DONE"]];
	} else {
		[ProgressHUD showError];
	}
	[ProgressHUD dismissAfterDelay:2];
}
+ (void)saveSnap:(id)arg1 withImage:(UIImage *)arg2 completion:(void (^)(BOOL success, NSError *error))arg3 {

	UIViewController *rootVC = [[[UIApplication sharedApplication] keyWindow] rootViewController];
	[SCAppDelSaver showSaveAlertIfNeededForMediaType:0 controller:rootVC saveBlock:^(BOOL success) {

		BOOL isImageMedia = [[arg1 media] isImage];
		if (isImageMedia) {
			[SCAppDelSaver handleImageSave:arg2 fromController:rootVC completion:^(BOOL success, NSError *error){

				[[self class] handleSnapSaveCompletion:success];
			}];
		} else {
			BOOL isVideoMedia = [[arg1 media] isVideo];
			if (isVideoMedia) {
				NSString *mediaId = [[arg1 media] mediaId];
				NSString *videPath = [NSClassFromString(@"Media") videoPathWithMediaId:mediaId];
				[SCAppDelSaver handleVideoSave:videPath fromController:rootVC completion:^(BOOL success, NSError *error){
					[[self class] handleSnapSaveCompletion:success];
				}];
			}

		}
	}];
}

@end

