//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIKit.h>
#import <Foundation/Foundation.h>

@interface SCAppDelOperaSaver : NSObject
{
}

+ (void)mergeAudioFile:(id)arg1 andVideoFile:(id)arg2 completion:(CDUnknownBlockType)arg3;
+ (void)downloadFileFromURL:(id)arg1 completion:(void (^)(BOOL success, NSError *error))arg2;
+ (void)getVideoAndAudioURLsFromM3U8URL:(id)arg1 completion:(CDUnknownBlockType)arg2;
+ (void)generateVideoURLFromM3U8:(id)arg1 key:(id)arg2 iv:(id)arg3 completion:(CDUnknownBlockType)arg4;
+ (void)saveVideoFromLocalPath:(id)arg1 controller:(id)arg2;
+ (void)downloadAndSaveVideoFromURL:(id)arg1 controller:(id)arg2;
+ (void)saveImageFromOperaController:(id)arg1;
+ (void)handleStorySaveCompletion:(_Bool)arg1 afterDelay:(double)arg2;
+ (void)saveMediaFromOperaPageViewController:(id)arg1;

@end

