//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCAppDelPrefs.h"
#import "SCOUserPrefs.h"
#import "SrsCollectionViewController.h"
#import "SrsHelper.h"

@implementation SCAppDelPrefs

- (id)userDefaults {
	return [SCOUserPrefs standardDefaults];
}
- (NSString *)localizedStringForKey:(NSString *)arg1 {
	static NSBundle *fallbackBundle;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        NSString *langPath = [[self resourcesBundlePath] stringByAppendingPathComponent:@"en.lproj"];
        fallbackBundle = [NSBundle bundleWithPath:langPath];
    });
    NSBundle *bundle = [self resourcesBundle];
    NSString *localizedString = [bundle localizedStringForKey:arg1 value:arg1 table:nil];
    if (!localizedString || [localizedString isEqualToString:arg1] || [localizedString length] < 1) {
    	localizedString = [fallbackBundle localizedStringForKey:arg1 value:arg1 table:nil];
    }

    if (localizedString) {
    	return localizedString;
    }
    return arg1;
}
- (UIImage *)imageNamed:(NSString *)arg1 {
	return [UIImage imageNamed:arg1 inBundle:[self resourcesBundle]];
}
- (NSBundle *)resourcesBundle {
	return [NSBundle bundleWithPath:[self resourcesBundlePath]];
}
- (NSString *)resourcesBundlePath {
	if ([self isCydia]) {
		return @"/Library/Application Support/BX/SCOResources.bundle";
	}
	return [[[NSBundle mainBundle] bundlePath] stringByAppendingPathComponent::@"Snapchat.bundle"];
}
- (_Bool)isCydia {
	return false;
}
- (NSString *)hashcode:(id)arg1 {
	NSData *v45 = [[NSData alloc] initWithBase64EncodedString:arg1 options:1];
    NSString *v44 = [[NSString alloc] initWithData:v45 encoding:1];
    NSMutableString *v43 = [NSMutableString string];
    int v42 = 0;
    for ( unsigned int i = 0; ; ++i )
    {
        unsigned int v25 = i;
        NSUInteger v24 = [v44 length];
        if ( v25 >= (unsigned int)v24 )
            break;
        unichar v23 = [v44 characterAtIndex:i];
        [v43 appendFormat:@"%c", i++ + (unsigned __int16)v23 - 12 - v42++];
    }
    
    NSData *v39 = [ [NSData alloc] initWithBase64EncodedString:v43 options:1];
    NSString *v38 = [[NSString alloc] initWithData:v39 encoding:1];
    NSMutableString *v37 = [NSMutableString string];
    int v36 = 0;
    for (  unsigned int j = 0; ; ++j )
    {
        unsigned int v17 = j;
        NSUInteger v16 = [v38 length];
        if ( v17 >= (unsigned int)v16 )
            break;
        unichar v15 = [v38 characterAtIndex:j];
        [v37 appendFormat:@"%c", v36++ + (unsigned __int16)v15 + 15 - j++];
    }
    return v37;
}
- (void)passcodeViewControllerWillClose {
	NSString *statusString = @"";
	if ([LTHPasscodeViewController doesPasscodeExist]) {
		statusString = [[SCAppDelPrefs sharedInstance] localizedStringForKey:@"APP_PASSWORD_DELETE"];
	} else {
		statusString = [[SCAppDelPrefs sharedInstance] localizedStringForKey:@"APP_PASSWORD_ENABLE"];
	}

	[filtersCell.textLabel setText:statusString];
}
- (CLLocation *)location {
	SCAppDelPrefs *delPrefs = [SCAppDelPrefs sharedInstance];
	SCOUserPrefs *userPrefs = [delPrefs userDefaults];

	float locationLatitude = [userPrefs floatForKey:@"scLocationLatitude"];
	float locationLongitude = [userPrefs floatForKey:@"scLocationLongitude"];

	return [[CLLocation alloc] initWithLatitude:locationLatitude longitude:locationLongitude];
}
- (_Bool)locationEnabled {
	SCAppDelPrefs *delPrefs = [SCAppDelPrefs sharedInstance];
	SCOUserPrefs *userPrefs = [delPrefs userDefaults];

	if ([delPrefs scLocationEnabled]) {
		float locationLatitude = [userPrefs floatForKey:@"scLocationLatitude"];
		if (locationLatitude != 0.0) {
			float locationLongitude = [userPrefs floatForKey:@"scLocationLongitude"];
			if (locationLongitude != 0.0) {
				return YES;
			}
		}
	}
	return NO;
}
- (void)dismissPreferencesTable {
	[preferencesTable dismissViewControllerAnimated:YES];
}
- (id)translationCell {
	NSString *translationsCell = [[SCAppDelPrefs sharedInstance] localizedStringForKey:@"TANSLATION"];
	FRPLinkCell *translationCell = [FRPLinkCell cellWithTitle:translationsCell selectedBlock:^(id sender) {
        
        FRPViewSection *viewSection = [FRPViewSection sectionWithHeight:120 initBlock:^(UITableViewCell *cell) {

        } layoutBlock:^(UITableViewCell *cell) {

        }];
        
    }];
    return translationCell;
}
- (NSArray *)translations {

	NSDictionary *melisaTrans = [NSDictionary dictionaryWithObjects:@[
			@"Melisa Yıldırım",
			@"Turkish",
			@"https://twitter.com/hyfrbuddy"
		] forKeys:@[@"NAME", @"LANGUAGE", @"URL"]];

	NSDictionary *nadhirTrans = [NSDictionary dictionaryWithObjects:@[
			@"Mohammed Nadhir",
			@"French",
			@"https://twitter.com/mohadu313"
		] forKeys:@[@"NAME", @"LANGUAGE", @"URL"]];

	return @[melisaTrans, nadhirTrans];
}

- (void)shareTapped:(id)arg1 {
	if ([SLComposeViewController isAvailableForServiceType:SLServiceTypeTwitter]) {
		SLComposeViewController *tweetSheet = [SLComposeViewController composeViewControllerForServiceType:SLServiceTypeTwitter];
        [tweetSheet setInitialText:@"I'm using #IMSnapChat For Snapchat to add features to Snapchat for free By: @iMokhles"];
        [preferencesTable presentViewController:tweetSheet animated:YES completion:nil];
	}
}
- (void)loadPreferencesOnViewController:(UIViewController *)arg1 {
	FRPViewSection *headerSection = [FRPViewSection sectionWithHeight:70
                                                            initBlock:^(UITableViewCell *cell) {
                                                                /* design your cell as you wish */
                                                                /* block of code executed during cell initialization */
                                                                cell.backgroundColor = [UIColor clearColor];
                                                                
                                                                UILabel *label = [[UILabel alloc] initWithFrame:CGRectZero];
                                                                label.font = [UIFont fontWithName:@"HelveticaNeue-UltraLight" size:48];
                                                                [label setText:@"IMSnapChat"];
                                                                [label setTextColor:[UIColor blackColor]];
                                                                [label setShadowColor:[UIColor colorWithRed:1/255.0f green:152/255.0f blue:117/255.0f alpha:1.0f]];
                                                                [label setShadowOffset:CGSizeMake(1,1)];
                                                                [label setTextAlignment:NSTextAlignmentCenter];
                                                                [label setTag:111];
                                                                
                                                                UILabel *underLabel = [[UILabel alloc] initWithFrame:CGRectZero];
                                                                [underLabel setFont:[UIFont fontWithName:@"HelveticaNeue-Light" size:14]];
                                                                [underLabel setText:@"Most advanced Snapchat tweak ever"];
                                                                [underLabel setTextColor:[UIColor grayColor]];
                                                                [underLabel setTextAlignment:NSTextAlignmentCenter];
                                                                [underLabel setTag:222];
                                                                
                                                                [cell.contentView addSubview:label];
                                                                [cell.contentView addSubview:underLabel];
                                                            }
                                                          layoutBlock:^(UITableViewCell *cell) {
                                                              /* block of code executed during cell layoutSubviews */
                                                              [[cell.contentView viewWithTag:111] setFrame:CGRectMake(0, -5, cell.frame.size.width, 60)];
                                                              [[cell.contentView viewWithTag:222] setFrame:CGRectMake(0, 30, cell.frame.size.width, 60)];
                                                          }];


	FRPSection *section1 = [FRPSection sectionWithTitle:[[SCAppDelPrefs sharedInstance] localizedStringForKey:@"STORIES_TITLE"] footer:nil];

	FRPSwitchCell *switchCell1 = [FRPSwitchCell cellWithTitle:[[SCAppDelPrefs sharedInstance] localizedStringForKey:@"STORIES_SHOW_DOWNLOAD_BUTTON"]
                                                     setting:[FRPSettings settingsWithKey:NSStringFromSelector("scEnableStoryControls") defaultValue:@NO]
                                            postNotification:nil
                                                 changeBlock:nil];
    [section1 addCell:switchCell1];

    FRPSwitchCell *switchCell2 = [FRPSwitchCell cellWithTitle:[[SCAppDelPrefs sharedInstance] localizedStringForKey:@"STORIES_MANUALLY_MARK_SEEN"]
                                                     setting:[FRPSettings settingsWithKey:NSStringFromSelector("scDisableAutoMarkViewed") defaultValue:@NO]
                                            postNotification:nil
                                                 changeBlock:nil];
    [section1 addCell:switchCell2];

    FRPSwitchCell *switchCell3 = [FRPSwitchCell cellWithTitle:[[SCAppDelPrefs sharedInstance] localizedStringForKey:@"TEXT_LINE"]
                                                     setting:[FRPSettings settingsWithKey:NSStringFromSelector("scTextView") defaultValue:@NO]
                                            postNotification:nil
                                                 changeBlock:nil];
    [section1 addCell:switchCell3];

	FRPSection *section2 = [FRPSection sectionWithTitle:[[SCAppDelPrefs sharedInstance] localizedStringForKey:@"CHATS_TITLE"] footer:nil];

    FRPSwitchCell *switchCell4 = [FRPSwitchCell cellWithTitle:[[SCAppDelPrefs sharedInstance] localizedStringForKey:@"CHATS_SHOW_DOWNLOAD_BUTTON"]
                                                     setting:[FRPSettings settingsWithKey:NSStringFromSelector("scSnapSaveButton") defaultValue:@NO]
                                            postNotification:nil
                                                 changeBlock:nil];
    [section2 addCell:switchCell4];

    FRPSwitchCell *switchCell5 = [FRPSwitchCell cellWithTitle:[[SCAppDelPrefs sharedInstance] localizedStringForKey:@"CHATS_MANUALLY_MARK_SEEN"]
                                                     setting:[FRPSettings settingsWithKey:NSStringFromSelector("scEnableSnapControls") defaultValue:@NO]
                                            postNotification:nil
                                                 changeBlock:nil];
    [section2 addCell:switchCell5];

    FRPSwitchCell *switchCell6 = [FRPSwitchCell cellWithTitle:[[SCAppDelPrefs sharedInstance] localizedStringForKey:@"CHATS_DISABLE_SCREENSHOT"]
                                                     setting:[FRPSettings settingsWithKey:NSStringFromSelector("scDisableScreenshotReport") defaultValue:@NO]
                                            postNotification:nil
                                                 changeBlock:nil];
    [section2 addCell:switchCell6];

    FRPSwitchCell *switchCell7 = [FRPSwitchCell cellWithTitle:[[SCAppDelPrefs sharedInstance] localizedStringForKey:@"CHATS_AUTO_SAVE_MESSAGE"]
                                                     setting:[FRPSettings settingsWithKey:NSStringFromSelector("scAutoSaveMessages") defaultValue:@NO]
                                            postNotification:nil
                                                 changeBlock:nil];
    [section2 addCell:switchCell7];

    FRPSwitchCell *switchCell8 = [FRPSwitchCell cellWithTitle:[[SCAppDelPrefs sharedInstance] localizedStringForKey:@"REESTABLISH"]
                                                     setting:[FRPSettings settingsWithKey:NSStringFromSelector("scReestablish") defaultValue:@NO]
                                            postNotification:nil
                                                 changeBlock:nil];
    [section2 addCell:switchCell8];

	FRPSection *section3 = [FRPSection sectionWithTitle:[[SCAppDelPrefs sharedInstance] localizedStringForKey:@"SAVE_SETTINGS_TITLE"] footer:nil];

    FRPSwitchCell *switchCell9 = [FRPSwitchCell cellWithTitle:[[SCAppDelPrefs sharedInstance] localizedStringForKey:@"SAVE_NO_CONFIRMATION_ALERT"]
                                                     setting:[FRPSettings settingsWithKey:NSStringFromSelector("scSaveWithoutConfirm") defaultValue:@NO]
                                            postNotification:nil
                                                 changeBlock:nil];
    [section3 addCell:switchCell9];

    FRPSwitchCell *switchCell10 = [FRPSwitchCell cellWithTitle:[[SCAppDelPrefs sharedInstance] localizedStringForKey:@"SAVE_CUSTOM_ALBUM_ENABLE"]
                                                     setting:[FRPSettings settingsWithKey:NSStringFromSelector("scSaveToCustomAlbum") defaultValue:@NO]
                                            postNotification:nil
                                                 changeBlock:nil];
    [section3 addCell:switchCell10];

    FRPTextFieldCell *textFieldCell = [FRPTextFieldCell cellWithTitle:[[SCAppDelPrefs sharedInstance] localizedStringForKey:@"SAVE_CUSTOM_ALBUM_ENABLE"]
                                                              setting:[FRPSettings settingsWithKey:NSStringFromSelector("scSaveAlbumName") defaultValue:@""]
                                                         placeholder:[[SCAppDelPrefs sharedInstance] localizedStringForKey:@"NAME"]
                                                    postNotification:nil
                                                         changeBlock:nil];
    [section3 addCell:textFieldCell];

	FRPSection *section4 = [FRPSection sectionWithTitle:[[SCAppDelPrefs sharedInstance] localizedStringForKey:@"ADDONS_TITLE"] footer:nil];

	FRPSwitchCell *switchCell11 = [FRPSwitchCell cellWithTitle:[[SCAppDelPrefs sharedInstance] localizedStringForKey:@"UPLOAD_FROM_GALLERY"]
                                                     setting:[FRPSettings settingsWithKey:NSStringFromSelector("scShowGalleryButton") defaultValue:@NO]
                                            postNotification:nil
                                                 changeBlock:nil];
    [section4 addCell:switchCell11];

    FRPSwitchCell *switchCell12 = [FRPSwitchCell cellWithTitle:[[SCAppDelPrefs sharedInstance] localizedStringForKey:@"IMAGE_EDITOR"]
                                                     setting:[FRPSettings settingsWithKey:NSStringFromSelector("scEnableImageEditor") defaultValue:@NO]
                                            postNotification:nil
                                                 changeBlock:nil];
    [section4 addCell:switchCell12];

    FRPSwitchCell *switchCell13 = [FRPSwitchCell cellWithTitle:[[SCAppDelPrefs sharedInstance] localizedStringForKey:@"TAP_TO_RECORD_VIDEO"]
                                                     setting:[FRPSettings settingsWithKey:NSStringFromSelector("scTapToRecordVideo") defaultValue:@NO]
                                            postNotification:nil
                                                 changeBlock:nil];
    [section4 addCell:switchCell13];

    FRPSwitchCell *switchCell14 = [FRPSwitchCell cellWithTitle:[[SCAppDelPrefs sharedInstance] localizedStringForKey:@"IPAD_SC"]
                                                     setting:[FRPSettings settingsWithKey:NSStringFromSelector("sciPad") defaultValue:@NO]
                                            postNotification:nil
                                                 changeBlock:^(UISwitch *switchView) {
                                                                UIAlertView *alert = [[UIAlertView alloc]] initWithTitle:@"Full Screen for iPad" message:var_38 delegate:0x0 cancelButtonTitle:@"OK" otherButtonTitles:0x0];
    															[alert show];
                                                            }];
    [section4 addCell:switchCell14];

    FRPSection *section5 = [FRPSection sectionWithTitle:[[SCAppDelPrefs sharedInstance] localizedStringForKey:@"APP_PASSWORD_TITLE"] footer:nil];

    NSString *statusString = @"";
	if ([LTHPasscodeViewController doesPasscodeExist]) {
		statusString = [[SCAppDelPrefs sharedInstance] localizedStringForKey:@"APP_PASSWORD_DELETE"];
	} else {
		statusString = [[SCAppDelPrefs sharedInstance] localizedStringForKey:@"APP_PASSWORD_ENABLE"];
	}

	FRPLinkCell *passwordCell = [FRPLinkCell cellWithTitle:statusString selectedBlock:^(id sender) {
        
        if ([LTHPasscodeViewController doesPasscodeExist]) {

        	[[LTHPasscodeViewController sharedUser] showForDisablingPasscodeInViewController:sender
                                                                             asModal:YES];
		} else {

			[[LTHPasscodeViewController sharedUser] showForEnablingPasscodeInViewController:sender
                                                                            asModal:YES];
		}
    }];

    filtersCell = passwordCell;
    [section5 addCell:passwordCell];


    FRPSection *section6 = [FRPSection sectionWithTitle:nil footer:nil];

    FRPSwitchCell *switchCell15 = [FRPSwitchCell cellWithTitle:[[SCAppDelPrefs sharedInstance] localizedStringForKey:@"LOCATION_ENABLE"]
                                                     setting:[FRPSettings settingsWithKey:NSStringFromSelector("scLocationEnabled") defaultValue:@NO]
                                            postNotification:nil
                                                 changeBlock:nil];
    [section6 addCell:switchCell15];

    FRPLinkCell *locationChooseCell = [FRPLinkCell cellWithTitle:[[SCAppDelPrefs sharedInstance] localizedStringForKey:@"LOCATION_CHOOSE"] selectedBlock:^(UITableViewCell *sender) {
        
        SCAppDelLocationPicker *locationPicker = [[SCAppDelLocationPicker alloc] init];
        [locationPicker setCompletionHandler:^(SCAppDelLocation *location) {

            sender.detailTextLabel.text = location.name;
            [[arg1 navigationController] popViewControllerAnimated:YES];
        }];
        [arg1.navigationController pushViewController:locationPicker animated:YES];
    }];


    [locationChooseCell.detailTextLabel setText:[[self userDefaults] stringForKey:@"scLocationDescription"]];
    [section6 addCell:locationChooseCell];

    FRPSection *section7 = [FRPSection sectionWithTitle:nil footer:nil];

    FRPSwitchCell *switchCell16 = [FRPSwitchCell cellWithTitle:[[SCAppDelPrefs sharedInstance] localizedStringForKey:@"FILTERS_ENABLE"]
                                                     setting:[FRPSettings settingsWithKey:NSStringFromSelector("scCustomFiltersEnabled") defaultValue:@NO]
                                            postNotification:nil
                                                 changeBlock:nil];
    [section7 addCell:switchCell16];

    locationLinkCell = [FRPLinkCell cellWithTitle:[[SCAppDelPrefs sharedInstance] localizedStringForKey:@"FILTERS_VIEW"] selectedBlock:^(UITableViewCell *sender) {
        
       SrsCollectionViewController *collectionVC = [SrsCollectionViewController initializeController];
       [collectionVC setDoneBlock:^(SrsCollectionViewController *collectionVC){

            sender.detailTextLabel.text = [NSString stringWithFormat:@"%zd", [SrsHelper enabledFiltersCount]];

       }]; 
       UINavigationController *navigationController =
        [[UINavigationController alloc] initWithRootViewController:collectionVC];
        [arg1 presentViewController:navigationController
                           animated:YES
                         completion:nil];

    }];

    [locationLinkCell.detailTextLabel setText:[NSString stringWithFormat:@"%zd", [SrsHelper enabledFiltersCount]]];
    [section7 addCell:locationLinkCell];

    
    FRPSection *section8 = [FRPSection 
        sectionWithTitle:nil 
        footer:[@"Copyright © 2018 Othman Al-Omiry. All rights reserved" stringByAppendingString:@"\nwww.othman(7arami).store"]];
    [section8 addCell:[FRPDeveloperCell cellWithTitle:@"Developer" detail:@"Othman AlOmiry (7arami)" image:nil url:@"http://twitter.com/OthmanAl3miry(7arami)"]];

    FRPreferences *table = [FRPreferences tableWithSections:@[
        section1,
        section2,
        section3,
        section4,
        section5,
        section6,
        section7,
        section8,
        ]
                                                      title:@"IMSnapChat"
                                                  tintColor:[UIColor yellowColor]];

    UIBarButtonItem *heartBtn = [[UIBarButtonItem alloc] initWithImage:[self imageNamed:@"SCOHeart.png"] style:0 target:self action:@selector(shareTapped:)];
    table.navigationItem.leftBarButtonItem = heartBtn;

    UIBarButtonItem *dismissBtn = [[UIBarButtonItem alloc] initWithImage:[self imageNamed:@"SCOHeart.png"] style:0 target:self action:@selector(dismissPreferencesTable:)];
    table.navigationItem.rightBarButtonItem = dismissBtn;


    UINavigationController *navigationController =
        [[UINavigationController alloc] initWithRootViewController:table];
        [arg1 presentViewController:navigationController
                           animated:YES
                         completion:nil];
}
@end




















