//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CoreLocation/CoreLocation.h>
#import <objc/runtime.h>
#import <UIKit/UIKit.h>
#import <Foundation/Foundation.h>
#import "vendors/PAPreferences/PAPreferences.h"
#import "vendors/LTHPasscodeViewController/LTHPasscodeViewController.h"
#import "vendors/FRPreferences/FRPrefs.h"

@class CLLocation, FRPLinkCell, FRPreferences, NSDictionary, NSString;

@interface SCAppDelPrefs : PAPreferences <LTHPasscodeViewControllerDelegate>
{
    FRPreferences *preferencesTable;
    FRPLinkCell *locationLinkCell;
    FRPLinkCell *filtersCell;
    FRPLinkCell *passcodeCell;
}

@property(retain, nonatomic) CLLocation *scLastLocation; // @synthesize scLastLocation=_scLastLocation;
@property(nonatomic) _Bool scDisableNewSnapchatLayout; // @synthesize scDisableNewSnapchatLayout=_scDisableNewSnapchatLayout;
- (id)userDefaults;
- (id)localizedStringForKey:(id)arg1;
- (UIImage *)imageNamed:(id)arg1;
- (NSBundle *)resourcesBundle;
- (NSString *)resourcesBundlePath;
- (_Bool)isCydia;
- (id)hashcode:(id)arg1;
- (void)passcodeViewControllerWillClose;
- (id)location;
- (_Bool)locationEnabled;
- (void)dismissPreferencesTable;
- (id)translationCell;
- (id)translations;
- (void)shareTapped:(id)arg1;
- (void)loadPreferencesOnViewController:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(nonatomic) _Bool scAutoSaveMessages; // @dynamic scAutoSaveMessages;
@property(nonatomic) _Bool scBlockCall; // @dynamic scBlockCall;
@property(nonatomic) _Bool scCustomFiltersEnabled; // @dynamic scCustomFiltersEnabled;
@property(nonatomic) _Bool scDisableAutoMarkViewed; // @dynamic scDisableAutoMarkViewed;
@property(nonatomic) _Bool scDisableScreenshotReport; // @dynamic scDisableScreenshotReport;
@property(nonatomic) _Bool scEnableFriendGroups; // @dynamic scEnableFriendGroups;
@property(nonatomic) _Bool scEnableImageEditor; // @dynamic scEnableImageEditor;
@property(nonatomic) _Bool scEnableSnapControls; // @dynamic scEnableSnapControls;
@property(nonatomic) _Bool scEnableStoryControls; // @dynamic scEnableStoryControls;
@property(nonatomic) NSDictionary *scFriendGroups; // @dynamic scFriendGroups;
@property(nonatomic) _Bool scHDPhoto; // @dynamic scHDPhoto;
@property(nonatomic) _Bool scHideDiscover; // @dynamic scHideDiscover;
@property(nonatomic) _Bool scIncreaseVideoDuration0; // @dynamic scIncreaseVideoDuration0;
@property(nonatomic) _Bool scLocationEnabled; // @dynamic scLocationEnabled;
@property(nonatomic) _Bool scLoops; // @dynamic scLoops;
@property(nonatomic) _Bool scReestablish; // @dynamic scReestablish;
@property(nonatomic) NSString *scSaveAlbumName; // @dynamic scSaveAlbumName;
@property(nonatomic) _Bool scSaveToCustomAlbum; // @dynamic scSaveToCustomAlbum;
@property(nonatomic) _Bool scSaveWithoutConfirm; // @dynamic scSaveWithoutConfirm;
@property(nonatomic) _Bool scShowGalleryButton; // @dynamic scShowGalleryButton;
@property(nonatomic) _Bool scShowStoriesTimer; // @dynamic scShowStoriesTimer;
@property(nonatomic) _Bool scSnap6; // @dynamic scSnap6;
@property(nonatomic) _Bool scSnapSaveButton; // @dynamic scSnapSaveButton;
@property(nonatomic) _Bool scTapToRecordVideo; // @dynamic scTapToRecordVideo;
@property(nonatomic) _Bool scTextView; // @dynamic scTextView;
@property(nonatomic) _Bool scTyping; // @dynamic scTyping;
@property(nonatomic) _Bool sciPad; // @dynamic sciPad;
@property(readonly) Class superclass;

@end

