//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CoreLocation/CoreLocation.h>
#import <objc/runtime.h>
#import <UIKit/UIKit.h>
#import <Foundation/Foundation.h>
#import "../vendors/KGWLocationPicker/KGWLocationPickerViewController.h"
#import "SCAppDelLocation.h"

@class SCAppDelLocationPicker;
typedef void(^SCAppDelLocationBlock)(SCAppDelLocation *location);

@interface SCAppDelLocationPicker : UITableViewController <UISearchBarDelegate, UISearchControllerDelegate, UISearchResultsUpdating>


+ (void)configureCell:(id)arg1 withLocation:(id)arg2;
+ (void)applyInitialCellConfigurations:(id)arg1;
@property(retain, nonatomic) KGWLocationPickerViewController *pickerViewController; // @synthesize pickerViewController=_pickerViewController;
@property(retain, nonatomic) NSMutableArray *locations; // @synthesize locations=_locations;
@property(retain, nonatomic) UISearchController *searchController; // @synthesize searchController=_searchController;
@property(retain, nonatomic) SCAppDelLocationPickerResults *resultsController; // @synthesize resultsController=_resultsController;
@property(copy, nonatomic) SCAppDelLocationBlock completionHandler; // @synthesize completionHandler=_completionHandler;

- (void)updateSearchResultsForSearchController:(UISearchController *)arg1;
- (void)searchBarSearchButtonClicked:(UISearchBar *)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)setupSearchController;
- (void)loadDataSources;
- (void)showPicker;
- (void)dismissController;
- (void)saveLocation:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)dismiss;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

