//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2017 17:44:06).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIKit.h>
#import <Foundation/Foundation.h>

typedef void(^SCOEditGroupSaveBlock)(SCOGroup *group);


@interface SCOEditGroupViewController : UITableViewController <UITextFieldDelegate>

@property(retain, nonatomic) UITextField *textfield; // @synthesize textfield=_textfield;
@property(nonatomic) _Bool editingGroup; // @synthesize editingGroup=_editingGroup;
@property(copy, nonatomic) SCOEditGroupSaveBlock saveBlock; // @synthesize saveBlock=_saveBlock;
@property(retain, nonatomic) NSMutableArray *selectedUsernames; // @synthesize selectedUsernames=_selectedUsernames;
@property(retain, nonatomic) SCOGroup *group; // @synthesize group=_group;
@property(retain, nonatomic) NSArray *allFriends; // @synthesize allFriends=_allFriends;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (void)viewDidLayoutSubviews;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)saveButtonPressed;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithGroup:(id)arg1 saveBlock:(void (^)(SCOGroup *group))arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end
