//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SrCollectionViewCell.h"
#import "../vendors/PureLayout/ALView+PureLayout.h"

@implementation SrCollectionViewCell
+ (UICollectionViewFlowLayout *)cellLayout {
	UICollectionViewFlowLayout *layout = [[UICollectionViewFlowLayout alloc] init];
	[layout setScrollDirection:0];
	[layout setSectionInset:UIEdgeInsetsMake(124, 0, 0, 0)];
	[layout setMinimumInteritemSpacing:4.0];
	[layout setMinimumLineSpacing:4.0];
	[layout setHeaderReferenceSize:CGSizeMake(100, 100)];
	[self setItemSize:[self cellSize]];

	return layout;
}
+ (CGSize)cellSize {

	return CGSizeMake(100, 100);
}

- (id)initWithFrame:(CGRect)frame
{
    self = [super initWithFrame:frame];
    if (self) {
        [self initialize];
    }
    return self;
}
- (id)initWithCoder:(NSCoder *)aDecoder {
    self = [super initWithCoder:aDecoder];
    if (self) {
        [self initialize];
    }
    return self;
}
- (void)initialize {
	[self setBackgroundColor:[[UIColor lightGrayColor] colorWithAlphaComponent:0.8]];
	
	self.imageView = [[UIImageView alloc] initWithFrame:CGRectZero];
	[self.imageView setContentMode:1];
	[self.imageView setClipsToBounds:YES];
	[self.contentView addSubview:self.imageView];
	[self.imageView autoPinEdgesToSuperviewEdges];


	self.selectionView = [[UIView alloc] initWithFrame:CGRectZero];
	[self.selectionView setHidden:YES];
	[self.selectionView setBackgroundColor:[[UIColor whiteColor] colorWithAlphaComponent:0.8]];
	[self.contentView addSubview:self.selectionView];
	[self.selectionView autoPinEdgesToSuperviewEdges];

	UIView *selectionSub = [[UIView alloc] initWithFrame:CGRectZero];
	[selectionSub setHidden:YES];
	[selectionSub setBackgroundColor:[UIColor whiteColor]];
	[selectionSub.layer setCornerRadius:10];
	[selectionSub.layer setMasksToBounds:YES];

	[self.selectionView addSubview:selectionSub];
	[selectionSub autoPinEdgeToSuperviewEdge:2 withInset:0.9];
	[selectionSub autoPinEdgeToSuperviewEdge:4 withInset:0.9];
	[selectionSub autoSetDimensionsToSize:CGSizeMake(100, 100)];
	[selectionSub autoCenterInSuperview];
}

- (void)setFilterSelected:(_Bool)arg1 {
	if (arg1) {
		[self.selectionView setHidden:NO];
	} else {
		[self.selectionView setHidden:YES];
	}
}

@end

