//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIKit.h>
#import <Foundation/Foundation.h>
#import "SrCollectionViewCell.h"
#import "Srs.h"

@class SrsCollectionViewController;
typedef void(^SrsCollectionViewBlock)(SrsCollectionViewController *collectionVC);

@interface SrsCollectionViewController : UICollectionViewController <UIImagePickerControllerDelegate, UINavigationControllerDelegate, UIGestureRecognizerDelegate>

+ (id)initializeController;
@property(retain, nonatomic) UIRefreshControl *refreshControl; // @synthesize refreshControl=_refreshControl;
@property(retain, nonatomic) NSMutableArray *enabledFiltersKeys; // @synthesize enabledFiltersKeys=_enabledFiltersKeys;
@property(retain, nonatomic) NSMutableArray *filters; // @synthesize filters=_filters;
@property(copy, nonatomic) SrsCollectionViewBlock doneBlock; // @synthesize doneBlock=_doneBlock;
- (UIImage *)emptyImage;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (void)updateTitle;
- (void)loadDataSource;
- (void)imagePickerControllerDidCancel:(id)arg1;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)showImagePicker;
- (void)openDirectory;
- (void)didTapAdd;
- (void)didTapDone;
- (void)handleLongPress:(id)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

