//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@implementation UIView (SnapAppDel)
- (void)addEditButtonWithRightButton:(UIButton *)arg1 {
	if (arg1) {
		UIButton *button = [self snapAppDelMarkReadButton];
		if (!button) {
			button = [[UIButton alloc] initForAutoLayout];
			UIImage *btnImage = [[SCAppDelPrefs sharedInstance] imageNamed:@"SCOEditButton"];
			btnImage = [btnImage imageWithRenderingMode:2];
			[button setImage:btnImage forState:0];
			[button setTintColor:[UIColor whiteColor]];
			[button setTag:413102];
			[button setTranslatesAutoresizingMaskIntoConstraints:0];
			[self addSubview:button];
			[button autoSetDimensionsToSize:CGSizeMake(100, 100)];
			[button autoAlignAxis:10 toSameAxisOfView:arg1 withOffset:2.0];
			[button autoPinEdge:2 toEdge:1 ofView:arg1 withOffset:-8.0];
		}
	}
}
- (void)addNewEditButtonWithRightButton:(UIButton *)arg1 {
	if (arg1) {
		UIButton *button = [self snapAppDelMarkReadButton];
		if (!button) {
			button = [[UIButton alloc] initForAutoLayout];
			UIImage *btnImage = [[SCAppDelPrefs sharedInstance] imageNamed:@"SCOEditButton"];
			btnImage = [btnImage imageWithRenderingMode:2];
			[button setImage:btnImage forState:0];
			[button setTintColor:[UIColor whiteColor]];
			[button setTag:413102];
			[button setTranslatesAutoresizingMaskIntoConstraints:0];
			[self addSubview:button];
			[button autoSetDimensionsToSize:CGSizeMake(100, 100)];
			[button autoPinEdge:2 toEdge:1 ofView:arg1 withOffset:-8.0];
			[button autoPinEdgeToSuperviewEdge:3 withInset:13];
		}
	}
}
- (UIButton *)snapAppDelEditButton {
	return [self viewWithTag:413102];
}
- (void)snapAppDelAddMarkReadButttonWithRightInset:(long long)arg1 bottomInset:(long long)arg2 {

	UIButton *button = [self snapAppDelMarkReadButton];
	if (!button) {
		button = [[UIButton alloc] init];
		[button setFrame:CGRectMake(10, 10, 10, 10)];
		[button setImage:[UIImage imageNamed:@"SC_Opera_ViewedCount_Icon_White"] forState:0];
		[button setTintColor:[UIColor whiteColor]];
		[button setTag:452131];
		[self addSubview:button];
		[button autoPinEdgeToSuperviewEdge:2 withInset:arg1];
		[button autoPinEdgeToSuperviewEdge:4 withInset:arg2];
		[button autoSetDimensionsToSize:CGSizeMake(100, 100)];
	}
}
- (UIButton *)snapAppDelMarkReadButton {
	return [self viewWithTag:452131];
}
- (void)snapAppDelAddSaveButtonWithRightInset:(long long)arg1 bottomInset:(long long)arg2 {

	UIButton *button = [self snapAppDelSaveButton];
	if (!button) {
		button = [[UIButton alloc] init];
		[button setFrame:CGRectMake(10, 10, 10, 10)];
		[button setImage:[UIImage imageNamed:@"save_button"] forState:0];
		[button setTag:531512];
		[self addSubview:button];
		[button autoPinEdgeToSuperviewEdge:2 withInset:arg1];
		[button autoPinEdgeToSuperviewEdge:4 withInset:arg2];
		[button autoSetDimensionsToSize:CGSizeMake(100, 100)];
	}
}
- (UIButton *)snapAppDelSaveButton {
	return [self viewWithTag:531512];
}
- (void)snapAppDelAddMarkReadButtton {
	[self snapAppDelAddMarkReadButttonWithRightInset:60 bottomInset:10];
}
- (void)snapAppDelAddSaveButton {

	[self snapAppDelAddSaveButtonWithRightInset:12 bottomInset:10];
}
@end

