//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface UIView (SnapAppDel)
- (void)addEditButtonWithRightButton:(UIButton *)arg1;
- (void)addNewEditButtonWithRightButton:(UIButton *)arg1;
- (UIButton *)snapAppDelEditButton;
- (void)snapAppDelAddMarkReadButttonWithRightInset:(long long)arg1 bottomInset:(long long)arg2;
- (UIButton *)snapAppDelMarkReadButton;
- (void)snapAppDelAddSaveButtonWithRightInset:(long long)arg1 bottomInset:(long long)arg2;
- (UIButton *)snapAppDelSaveButton;
- (void)snapAppDelAddMarkReadButtton;
- (void)snapAppDelAddSaveButton;
@end

