//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2017 17:44:06).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIKit.h>
#import "CircleProgressBar.h"


@interface CircleProgressBarHandler : NSObject
@property(retain, nonatomic) CircleProgressBar *circleProgressBar; // @synthesize circleProgressBar=_circleProgressBar;
@property(retain, nonatomic) UIView *circleView; // @synthesize circleView=_circleView;
- (void)startTimerWithSeconds:(long long)arg1;
- (void)createViewWithFrame:(struct CGRect)arg1;
- (id)initWithCircleFrame:(struct CGRect)arg1;

@end

