//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCOGroup.h"

@implementation SCOGroup

+ (SCOGroup *)newGroup {
  SCOGroup *group = [[SCOGroup alloc] init];
  [group setKey:[[NSUUID UUID] UUIDString]];
  [group setFriends:@[]];

  return group;
}
+ (SCOGroup *)groupFromDictionary:(NSDictionary *)arg1 withKey:(NSString *)arg2 {

  SCOGroup *group = [[SCOGroup alloc] init];
  [group setKey:arg2];
  [group setTitle:[arg1 objectForKey:@"title"]];
  if ([arg1 objectForKey:@"friends"]) {
    [group setFriends:[arg1 objectForKey:@"friends"]];
  } else {
    [group setFriends:@[]];
  }

  if ([group key]) {
    return group;
  }

  return nil;

}
- (NSMutableDictionary *)groupDictionary {
  NSMutableDictionary *dict = [NSMutableDictionary new];
  if ([self title]) {
    [dict setObject:[self title] forKey:@"title"];
  }

  if ([self friends]) {
    [dict setObject:[self friends] forKey:@"friends"];
  }

  return dict;
}
@end
