//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIKit.h>
#import <Foundation/Foundation.h>


@interface SrsAppDel : NSObject


+ (NSMutableDictionary *)filtersByAddingAppDelFiltersToSnapchatDictionaryFilters:(NSDictionary *)arg1;
+ (NSMutableArray *)filtersByAddingAppDelFiltersToSnapchatFilters:(NSArray *)arg1;
+ (void)fetchAppDelFiltersWithCompletion:(void (^)(NSArray *filters))completion;
+ (NSString *)scoffiltersDirectoryPath;
+ (SrsAppDel *)sharedInstance;
@property(retain, nonatomic) NSDictionary *appDelFiltersDictionaryForSnapchat; // @synthesize appDelFiltersDictionaryForSnapchat=_appDelFiltersDictionaryForSnapchat;
@property(retain, nonatomic) NSArray *appDelFiltersForSnapchat; // @synthesize appDelFiltersForSnapchat=_appDelFiltersForSnapchat;
- (void)updateAppDelFiltersForSnapchatWithCompletion:(void (^)(NSArray *filters, NSDictionary *filtersDict))completion;

@end
