//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/Foundation.h>

//#import "NSCoding-Protocol.h"

//@class AVPlayerItem, AVURLAsset, MediaUpdateListenerAnnouncer, NSData, NSNumber, NSString, SOJUMediaUrl, SOJUStoryCaption;
//@protocol BaseNoteMediaProcessingDelegate, MediaCacheInfoDataSource, MediaDataSource, MediaDelegate, MediaImageProcessingDelegate, MediaUploadDelegate, SCMediaDownloadUnarchiver, SCMediaUploadArchiver;

@interface Media : NSObject <NSCoding>
//{
//    MediaUpdateListenerAnnouncer *_updateAnnouncer;
//    _Bool _overlayPresent;
//    _Bool _isThumbnail;
//    _Bool _isLoading;
//    _Bool _finishedPlaying;
//    id <MediaCacheInfoDataSource> _cacheInfoDataSource;
//    id <MediaDataSource> _dataSource;
//    NSData *_mediaDataToUpload;
//    id <MediaDelegate> _delegate;
//    NSNumber *_captionScreenPosition;
//    NSNumber *_captionOrientation;
//    NSString *_captionText;
//    SOJUStoryCaption *_storyCaptionInfo;
//    NSString *_attachmentUrl;
//    NSString *_venueId;
//    NSData *_overlayDataToUpload;
//    AVPlayerItem *_playerItem;
//    id <MediaUploadDelegate> _uploadDelegate;
//    id <MediaImageProcessingDelegate> _imageProcessingDelegate;
//    id <BaseNoteMediaProcessingDelegate> _baseNoteMediaProcessingDelegate;
//    long long _loadContext;
//    id <SCMediaUploadArchiver> _uploadArchiver;
//    id <SCMediaDownloadUnarchiver> _downloadUnarchiver;
//    SOJUMediaUrl *_uploadURL;
//    AVURLAsset *_videoAsset;
//    unsigned long long _numBytes;
//    double _progress;
//}
//
//+ (id)_submitRequestQueue;
//+ (id)overlayPathWithMediaId:(id)arg1;
+ (id)videoPathWithMediaId:(id)arg1;
//+ (void)removeFromDiskWithMediaId:(id)arg1;
//+ (id)set;
//+ (long long)mediaTypeFromMedia:(id)arg1;
//+ (void)_postSnapSendingRequestWithEndpoint:(id)arg1 parameters:(id)arg2 uploadData:(id)arg3 successBlock:(CDUnknownBlockType)arg4 failureBlock:(CDUnknownBlockType)arg5;
//+ (void)retryDoublePostWithParameters:(id)arg1 uploadData:(id)arg2 successBlock:(CDUnknownBlockType)arg3 failureBlock:(CDUnknownBlockType)arg4;
//+ (void)doublePostWithParameters:(id)arg1 uploadData:(id)arg2 successBlock:(CDUnknownBlockType)arg3 failureBlock:(CDUnknownBlockType)arg4;
//+ (id)retryPostStoryWithParameters:(id)arg1 uploadData:(id)arg2 successBlock:(CDUnknownBlockType)arg3 failureBlock:(CDUnknownBlockType)arg4;
//+ (id)postStoryWithParameters:(id)arg1 uploadData:(id)arg2 successBlock:(CDUnknownBlockType)arg3 failureBlock:(CDUnknownBlockType)arg4;
//+ (void)retrySendSnapsWithParameters:(id)arg1 uploadData:(id)arg2 successBlock:(CDUnknownBlockType)arg3 failureBlock:(CDUnknownBlockType)arg4;
//+ (void)sendSnapWithParameters:(id)arg1 successBlock:(CDUnknownBlockType)arg2 failureBlock:(CDUnknownBlockType)arg3;
//+ (id)_uploadMediaWithEndpoint:(id)arg1 parameters:(id)arg2 uploadData:(id)arg3 maxNumRequestAttempts:(id)arg4 successBlock:(CDUnknownBlockType)arg5 failureBlock:(CDUnknownBlockType)arg6;
//+ (void)uploadBigMediaWithParameters:(id)arg1 uploadData:(id)arg2 successBlock:(CDUnknownBlockType)arg3 failureBlock:(CDUnknownBlockType)arg4;
//+ (id)uploadMediaWithParameters:(id)arg1 uploadData:(id)arg2 successBlock:(CDUnknownBlockType)arg3 failureBlock:(CDUnknownBlockType)arg4;
//+ (id)postStoriesWithParameters:(id)arg1 uploadData:(id)arg2 batchSuccessBlock:(CDUnknownBlockType)arg3 batchFailureBlock:(CDUnknownBlockType)arg4;
//+ (id)storyBuilderPostStoryWithParameters:(id)arg1 uploadData:(id)arg2 successBlock:(CDUnknownBlockType)arg3 failureBlock:(CDUnknownBlockType)arg4;
//+ (void)setDelegate:(id)arg1;
//+ (id)delegate;
//+ (void)setTopic:(id)arg1;
//+ (unsigned long long *)fasterCodingKeys;
//+ (unsigned long long)fasterCodingVersion;
//@property(nonatomic) _Bool finishedPlaying; // @synthesize finishedPlaying=_finishedPlaying;
//@property(nonatomic) double progress; // @synthesize progress=_progress;
//@property(readonly, nonatomic) _Bool isLoading; // @synthesize isLoading=_isLoading;
//@property(nonatomic) unsigned long long numBytes; // @synthesize numBytes=_numBytes;
//@property(retain, nonatomic) AVURLAsset *videoAsset; // @synthesize videoAsset=_videoAsset;
//@property(retain, nonatomic) SOJUMediaUrl *uploadURL; // @synthesize uploadURL=_uploadURL;
//@property(retain, nonatomic) id <SCMediaDownloadUnarchiver> downloadUnarchiver; // @synthesize downloadUnarchiver=_downloadUnarchiver;
//@property(retain, nonatomic) id <SCMediaUploadArchiver> uploadArchiver; // @synthesize uploadArchiver=_uploadArchiver;
//@property(nonatomic) _Bool isThumbnail; // @synthesize isThumbnail=_isThumbnail;
//@property(nonatomic) long long loadContext; // @synthesize loadContext=_loadContext;
//@property(nonatomic) __weak id <BaseNoteMediaProcessingDelegate> baseNoteMediaProcessingDelegate; // @synthesize baseNoteMediaProcessingDelegate=_baseNoteMediaProcessingDelegate;
//@property(nonatomic) __weak id <MediaImageProcessingDelegate> imageProcessingDelegate; // @synthesize imageProcessingDelegate=_imageProcessingDelegate;
//@property(nonatomic) __weak id <MediaUploadDelegate> uploadDelegate; // @synthesize uploadDelegate=_uploadDelegate;
//@property(retain, nonatomic) AVPlayerItem *playerItem; // @synthesize playerItem=_playerItem;
//@property(retain, nonatomic) NSData *overlayDataToUpload; // @synthesize overlayDataToUpload=_overlayDataToUpload;
//@property(nonatomic) _Bool overlayPresent; // @synthesize overlayPresent=_overlayPresent;
//@property(copy, nonatomic) NSString *venueId; // @synthesize venueId=_venueId;
//@property(copy, nonatomic) NSString *attachmentUrl; // @synthesize attachmentUrl=_attachmentUrl;
//@property(retain, nonatomic) SOJUStoryCaption *storyCaptionInfo; // @synthesize storyCaptionInfo=_storyCaptionInfo;
//@property(retain, nonatomic) NSString *captionText; // @synthesize captionText=_captionText;
//@property(retain, nonatomic) NSNumber *captionOrientation; // @synthesize captionOrientation=_captionOrientation;
//@property(retain, nonatomic) NSNumber *captionScreenPosition; // @synthesize captionScreenPosition=_captionScreenPosition;
//@property(nonatomic) __weak id <MediaDelegate> delegate; // @synthesize delegate=_delegate;
//@property(retain, nonatomic) NSData *mediaDataToUpload; // @synthesize mediaDataToUpload=_mediaDataToUpload;
//@property(nonatomic) __weak id <MediaDataSource> dataSource; // @synthesize dataSource=_dataSource;
//@property(nonatomic) __weak id <MediaCacheInfoDataSource> cacheInfoDataSource; // @synthesize cacheInfoDataSource=_cacheInfoDataSource;
//- (void).cxx_destruct;
//- (_Bool)_generateThumbnailForOperaFailFallback;
//- (_Bool)_generateThumbnailForOpera;
//- (id)_storyMediaCache;
//- (void)_fetchMediaInBackgroundQueueWithUserInitiated:(_Bool)arg1 withRequestBatchId:(id)arg2 completion:(CDUnknownBlockType)arg3;
//- (void)fetchMediaFailureHelper:(id)arg1;
//- (CDUnknownBlockType)_fetchMediaFailureCallbackWithCachedMediaId:(id)arg1 completion:(CDUnknownBlockType)arg2;
//- (CDUnknownBlockType)_fetchMediaSuccessCallbackWithCachedMediaId:(id)arg1 request:(id)arg2 completion:(CDUnknownBlockType)arg3;
//- (_Bool)isPsychomantis;
- (_Bool)isImage;
//- (_Bool)isVideoStreaming;
//- (_Bool)isVideoWithSound;
//- (_Bool)isSpectaclesVideo;
- (_Bool)isVideo;
//- (void)fetchMediaWithCompletion:(CDUnknownBlockType)arg1;
//- (void)fetchMediaUserInitiated:(_Bool)arg1 forPrefetch:(_Bool)arg2 withRequestBatchId:(id)arg3 completion:(CDUnknownBlockType)arg4;
//- (void)fetchMediaUserInitiated:(_Bool)arg1 forPrefetch:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
//- (void)fetchMediaUserInitiated:(_Bool)arg1 withRequestBatchId:(id)arg2 completion:(CDUnknownBlockType)arg3;
//- (void)fetchMediaUserInitiated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
//- (id)requestKey;
//- (void)imageProcessingDone;
//- (void)baseNoteMediaProcessingDone;
//- (void)gifFromCacheWithCompletion:(CDUnknownBlockType)arg1;
//- (void)imageFromCacheWithCompletion:(CDUnknownBlockType)arg1;
//- (_Bool)isReadyToDisplay;
//- (_Bool)isVideoUnarchived;
//- (id)overlayPath;
//- (void)fetchThumbnailDataWithCompletion:(CDUnknownBlockType)arg1;
//- (void)fetchOverlayDataWithCompletion:(CDUnknownBlockType)arg1;
//- (id)videoPathMP4;
//- (id)videoPath;
//- (id)thumbnailCacheId;
//- (void)_generateThumbnailWithOverlayData:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
//- (void)unarchiveMediaWithCompletion:(CDUnknownBlockType)arg1;
//- (void)initPlayerItemWithCompletion:(CDUnknownBlockType)arg1 freeAVPlayerItem:(_Bool)arg2;
//- (void)setPlayerItem:(id)arg1 freeAVPlayerItem:(_Bool)arg2;
//- (void)writeVideoToURL:(id)arg1 callbackOnMainThread:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
//- (void)writeVideoToURL:(id)arg1 completion:(CDUnknownBlockType)arg2;
//- (id)encryptor;
//- (void)_blobFromSCCacheWithCompletionHandler:(CDUnknownBlockType)arg1;
//- (void)storyBundleFromSCCacheWithCompletionBlock:(CDUnknownBlockType)arg1;
//- (void)_saveDataToSCCache:(id)arg1 alreadyEncrypted:(_Bool)arg2 useClientEncryption:(_Bool)arg3 successBlock:(CDUnknownBlockType)arg4 failureBlock:(CDUnknownBlockType)arg5;
//- (_Bool)_isChatMedia;
//- (_Bool)_isStoryMedia;
//- (void)saveDataToCache:(id)arg1 alreadyEncrypted:(_Bool)arg2 useClientEncryption:(_Bool)arg3 successBlock:(CDUnknownBlockType)arg4 failureBlock:(CDUnknownBlockType)arg5;
//- (void)saveDataToCache:(id)arg1 useClientEncryption:(_Bool)arg2;
//- (void)saveDataToCache:(id)arg1;
//- (void)streamingMediaFromCacheWithCompletionHandler:(CDUnknownBlockType)arg1;
//- (void)mediaFromCacheWithCompletionHandler:(CDUnknownBlockType)arg1;
//- (void)blobFromCacheWithCompletionHandler:(CDUnknownBlockType)arg1 shouldAttemptToUnzip:(_Bool)arg2;
//- (void)blobFromCacheWithCompletionHandler:(CDUnknownBlockType)arg1;
//- (void)storyBundleFromCacheWithCompletionBlock:(CDUnknownBlockType)arg1;
//- (void)archiveSnapData:(id)arg1 overlayData:(id)arg2 completion:(CDUnknownBlockType)arg3;
//- (void)unarchiveSnapAndOverlayFromData:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
//- (void)copyDataFromMedia:(id)arg1;
//- (void)setArchivedDataToUpload:(id)arg1;
//- (void)dataToUploadWithCompletion:(CDUnknownBlockType)arg1;
//- (id)dataToUpload;
//- (_Bool)isBroadcast;
- (id)mediaId;
//- (_Bool)isLoaded;
//- (void)removeFromDisk:(id)arg1;
//- (void)removeFromDiskMP4;
//- (void)removeFromDisk;
//- (void)removeFromCache;
//- (_Bool)hasSeparateCaption;
//@property(readonly, nonatomic) MediaUpdateListenerAnnouncer *updateAnnouncer;
//- (void)encodeWithCoder:(id)arg1;
//- (void)_mediaDidDecodeObject;
//- (void)didDecodeObject;
//- (id)initWithCoder:(id)arg1;
//- (id)description;
//- (id)initWithJSONDictionary:(id)arg1;
//- (long long)mediaType;
//- (void)_signedURLUploadWithParameters:(id)arg1 data:(id)arg2 snapType:(unsigned long long)arg3;
//- (void)bqUploadWithDataAndParameters:(id)arg1 parameters:(id)arg2 snapType:(unsigned long long)arg3;
//- (void)_uploadWithData:(id)arg1 parameters:(id)arg2;
//- (void)uploadWithData:(id)arg1;
//- (void)upload;
//- (void)setUInt64:(unsigned long long)arg1 forUInt64Key:(unsigned long long)arg2;
//- (void)setBool:(_Bool)arg1 forUInt64Key:(unsigned long long)arg2;
//- (void)setObject:(id)arg1 forUInt64Key:(unsigned long long)arg2;
//- (void)decodeWithFasterDecoder:(id)arg1;
//- (void)encodeWithFasterCoder:(id)arg1;
//- (_Bool)preferFasterCoding;

@end

