//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2017 17:44:06).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCChatBaseViewController.h"

//#import "SCActionMenuViewControllerDelegate-Protocol.h"
//#import "SCChatCashControllerDelegate-Protocol.h"
//#import "SCChatCellGestureDelegate-Protocol.h"
//#import "SCChatDelegate-Protocol.h"
//#import "SCChatDrawerSender-Protocol.h"
//#import "SCChatFullscreenMediaChatTableCellDelegate-Protocol.h"
//#import "SCChatHamburgerTableSectionFriendsDelegate-Protocol.h"
//#import "SCChatHamburgerTableSectionOneOnOneSettingDataSource-Protocol.h"
//#import "SCChatHamburgerTableSectionOneOnOneSettingDelegate-Protocol.h"
//#import "SCChatInputControllerDelegate-Protocol.h"
//#import "SCChatStoryDelegate-Protocol.h"
//#import "SCChatTableLongPressDelegate-Protocol.h"
//#import "SCChatUserProfileDataSource-Protocol.h"
//#import "SCChatUserProfileViewControllerDelegate-Protocol.h"
//#import "SCChatViewHeaderDataSource-Protocol.h"
//#import "SCChatViewModelListener-Protocol.h"
//#import "SCChatViewModelReducerVisibilityDelegate-Protocol.h"
//#import "SCDetectTouchViewDelegate-Protocol.h"
//#import "SCHeaderDelegate-Protocol.h"
//#import "SCOperaPresenterDelegate-Protocol.h"
//#import "SCPullToDismissControllerGestureDelegate-Protocol.h"
//#import "SCReplyDelegate-Protocol.h"
//#import "SCS2RStackDebuggable-Protocol.h"
//#import "SCSnapPlayContainer-Protocol.h"
//#import "SCSnapPlayDelegate-Protocol.h"
//#import "SCTimeProfilable-Protocol.h"
//#import "SKStoreProductViewControllerDelegate-Protocol.h"
//#import "UIGestureRecognizerDelegate-Protocol.h"
//#import "UIScrollViewDelegate-Protocol.h"

//@class NSMutableSet, NSString, SCActionMenuViewController, SCActionSheetCoordinator, SCBaseMediaFullScreenView, SCBaseMediaOperaPresenter, SCBitmojiAvatarPickerViewController, SCChat, SCChatAutoResponderController, SCChatCashController, SCChatCashMediatorV2, SCChatHamburgerTableSectionFriends, SCChatMessageReleaser, SCChatSendHelper, SCChatTableController, SCChatTableViewDelegate, SCChatUserProfileViewController, SCChatViewHeader, SCChatViewLifeCycleListenerAnnouncer, SCChatViewModelForChat, SCContextOperaPlaylistPlugin, SCCustomVolumeController, SCDetectTouchView, SCManagedCapturerState, SCModalHamburgerRootViewController, SCOperaPerformanceTrackingPlugin, SCOperaPlaylistCameraPlugin, SCOperaPlaylistNotificationOptInPlugin, SCOperaPlaylistStoriesPlugin, SCOperaPresenter, SCSearchStoriesPresenter, SCStoriesReplayManager, SCUserSession, UILongPressGestureRecognizer, UIPanGestureRecognizer, UITableView, UIWindow;
//@protocol SCChatStoryIconUpdater;

@interface SCChatViewControllerV2 : SCChatBaseViewController
//<SCActionMenuViewControllerDelegate, SCChatViewModelReducerVisibilityDelegate, SCChatTableLongPressDelegate, SCChatCashControllerDelegate, SCChatFullscreenMediaChatTableCellDelegate, SCChatViewHeaderDataSource, SCChatInputControllerDelegate, SCChatCellGestureDelegate, UIScrollViewDelegate, SCChatUserProfileDataSource, SCChatUserProfileViewControllerDelegate, SCHeaderDelegate, SCPullToDismissControllerGestureDelegate, SCSnapPlayContainer, SCSnapPlayDelegate, SCTimeProfilable, SKStoreProductViewControllerDelegate, UIGestureRecognizerDelegate, SCChatDrawerSender, SCChatViewModelListener, SCDetectTouchViewDelegate, SCChatDelegate, SCChatStoryDelegate, SCOperaPresenterDelegate, SCReplyDelegate, SCChatHamburgerTableSectionOneOnOneSettingDataSource, SCChatHamburgerTableSectionOneOnOneSettingDelegate, SCChatHamburgerTableSectionFriendsDelegate, SCS2RStackDebuggable>
//{
//    SCActionSheetCoordinator *_actionSheetCoordinator;
//    NSMutableSet *_clearChatTimers;
//    double _lastYOffset;
//    SCManagedCapturerState *_managedCapturerState;
//    NSString *_managedCapturerToken;
//    _Bool _isRegularSession;
//    _Bool _togglingCamera;
//    _Bool _isChatViewCentered;
//    _Bool _actionMenuShown;
//    _Bool _actionMenuOpening;
//    SCActionMenuViewController *_actionMenuViewController;
//    SCUserSession *_userSession;
//    SCChatTableController *_chatTableController;
//    SCChatViewHeader *_header;
//    SCChatMessageReleaser *_messageReleaser;
//    SCChatAutoResponderController *_autoResponderController;
//    SCChatCashMediatorV2 *_cashMediator;
//    SCChatCashController *_cashController;
//    unsigned long long _lastRecipientChatSequenceSounded;
//    long long _missCallType;
//    SCDetectTouchView *_detectTouchView;
//    SCBaseMediaOperaPresenter *_operaPresenter;
//    SCBitmojiAvatarPickerViewController *_avatarPickerVC;
//    SCChatSendHelper *_chatSendHelper;
//    SCSearchStoriesPresenter *_searchStoriesPresenter;
//    double _lastVerticalTranslateUp;
//    id <SCChatStoryIconUpdater> _chatStoryIconUpdater;
//    SCOperaPresenter *_storiesOperaPresenter;
//    SCOperaPlaylistStoriesPlugin *_storiesPlugin;
//    SCOperaPlaylistNotificationOptInPlugin *_optInPlugin;
//    SCOperaPerformanceTrackingPlugin *_performanceTrackingPlugin;
//    SCContextOperaPlaylistPlugin *_contextPlugin;
//    SCOperaPlaylistCameraPlugin *_cameraPlugin;
//    SCStoriesReplayManager *_storiesReplayManager;
//    SCChatHamburgerTableSectionFriends *_friendsSection;
//    SCChatViewLifeCycleListenerAnnouncer *_lifeCycleAnnouncer;
//    SCChat *_chat;
//    unsigned long long _deeplinkType;
//    SCChatViewModelForChat *_chatViewModel;
//    SCModalHamburgerRootViewController *_modalHamburgerViewController;
//    SCBaseMediaFullScreenView *_baseMediaFullScreenView;
//    UIWindow *_mediaFullScreenWindow;
//    SCChatUserProfileViewController *_chatUserProfileVC;
//    SCCustomVolumeController *_customVolumeController;
//    UILongPressGestureRecognizer *_longPressGestureRecognizer;
//    UIPanGestureRecognizer *_panGestureRecognizer;
//    double _snapViewingChatOffset;
//    SCChatTableViewDelegate *_tableDelegate;
//    UITableView *_tableView;
//}
//
- (id)getSnapPlayControllerInCurrentVC;
//+ (int)context;
//+ (id)pageViewName;
//@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
//@property(retain, nonatomic) SCChatTableViewDelegate *tableDelegate; // @synthesize tableDelegate=_tableDelegate;
//@property(nonatomic) double snapViewingChatOffset; // @synthesize snapViewingChatOffset=_snapViewingChatOffset;
//@property(retain, nonatomic) UIPanGestureRecognizer *panGestureRecognizer; // @synthesize panGestureRecognizer=_panGestureRecognizer;
//@property(retain, nonatomic) UILongPressGestureRecognizer *longPressGestureRecognizer; // @synthesize longPressGestureRecognizer=_longPressGestureRecognizer;
//@property(retain, nonatomic) SCCustomVolumeController *customVolumeController; // @synthesize customVolumeController=_customVolumeController;
//@property(retain, nonatomic) SCChatUserProfileViewController *chatUserProfileVC; // @synthesize chatUserProfileVC=_chatUserProfileVC;
//@property(retain, nonatomic) UIWindow *mediaFullScreenWindow; // @synthesize mediaFullScreenWindow=_mediaFullScreenWindow;
//@property(retain, nonatomic) SCBaseMediaFullScreenView *baseMediaFullScreenView; // @synthesize baseMediaFullScreenView=_baseMediaFullScreenView;
//@property(retain, nonatomic) SCModalHamburgerRootViewController *modalHamburgerViewController; // @synthesize modalHamburgerViewController=_modalHamburgerViewController;
//@property(retain, nonatomic) SCChatViewModelForChat *chatViewModel; // @synthesize chatViewModel=_chatViewModel;
//@property(nonatomic) unsigned long long deeplinkType; // @synthesize deeplinkType=_deeplinkType;
//@property(retain, nonatomic) SCChat *chat; // @synthesize chat=_chat;
//- (void)setLifeCycleAnnouncer:(id)arg1;
//- (id)lifeCycleAnnouncer;
//- (void).cxx_destruct;
//- (void)dismissActionMenu:(_Bool)arg1;
//- (id)messageViewModelWithMessageId:(id)arg1;
//- (void)hamburgerTableSectionOneOnOneSettingDidRemoveFriend:(id)arg1;
//- (void)hamburgerTableSectionOneOnOneSettingDidBlockFriend:(id)arg1;
//- (void)hamburgerTableSectionOneOnOneSettingDidUpdateUsername:(id)arg1;
//- (void)_cleanupHamburger;
//- (void)hamburgerTableSectionFriends:(id)arg1 askedToSwitchToChat:(id)arg2 deepLinkURL:(id)arg3;
//- (_Bool)shouldSuppressKeyboardFromDrawerVisible;
//- (_Bool)isFullScreenPlayerShown;
//- (void)updateTableContentInset:(double)arg1;
//- (_Bool)isViewPartiallyVisible;
//- (id)searchStoriesPresenter;
//- (id)operaPresenter;
//- (void)_switchChatTo:(id)arg1;
//- (_Bool)replyingToStoryWithChat;
//- (void)didFollowThrough;
//- (void)replyWithParameter:(id)arg1 completion:(CDUnknownBlockType)arg2;
//- (void)didTapAddButtonForSnapchatter:(id)arg1;
//- (void)presentMiniProfileForSnapchatter:(id)arg1 addSource:(long long)arg2;
//- (struct CGRect)_iconViewRectForIndexPath:(id)arg1;
//- (struct CGRect)iconViewRectForSnap:(id)arg1;
//- (_Bool)tableIsFadedOut;
//- (struct CGRect)_screenFrameExcludingHeader;
//- (struct CGRect)mediaBoundingFrame;
//- (_Bool)shouldDisableFullScreen;
//- (void)hideCustomVolumeView;
//- (void)showCustomVolumeViewIgnoringNextVolumeChange:(_Bool)arg1;
//- (void)mediaDidDismissFullscreen;
//- (void)mediaDidGoFullscreen:(_Bool)arg1;
//- (void)mediaWillGoFullscreen;
//- (void)didShowPendingDisplayForMessageId:(id)arg1 conversationId:(id)arg2;
//- (void)didShowCompleteDisplayForMessageId:(id)arg1 conversationId:(id)arg2;
//- (void)didSelectPreserveMessageForMessageId:(id)arg1 conversationId:(id)arg2;
//- (void)didRequestRetryFailedMessage:(id)arg1;
//- (void)didRequestStateUpdateForMessageCell:(id)arg1;
//- (void)didShouldShowGreetingStickerStateChange:(_Bool)arg1;
//- (void)didViewModelsChange;
//- (void)didReturnFromCameraWithoutSendingSnap;
//- (void)didPressSnapAccessoryButton;
//- (_Bool)chatInputControllerShouldAllowTextEditing:(id)arg1;
//- (void)enableTableViewInteractionAfterChatNotesRecording;
//- (void)disableTableViewInteractionBeforeChatNotesRecording;
//- (void)sendVideoNoteWithData:(id)arg1 duration:(double)arg2;
//- (void)sendAudioNoteWithData:(id)arg1 duration:(double)arg2;
//- (void)sendMediaDrawerMedia:(id)arg1 fromLocation:(CDStruct_1dee9796)arg2;
//- (void)sendSticker:(id)arg1 fromPack:(id)arg2 fromPosition:(unsigned long long)arg3 fromSource:(long long)arg4;
//- (void)_messageSendEpilogue;
//- (void)removeLifeCycleListener:(id)arg1;
//- (void)addLifeCycleListener:(id)arg1;
//- (unsigned long long)supportedInterfaceOrientations;
//- (void)userDidScreenRecord;
//- (void)userDidTakeScreenshot;
//- (void)sccpConnectionStatusChanged;
//- (void)_updateMessageStateForBaseMessage:(id)arg1 animated:(_Bool)arg2;
//- (void)_batchSaveOrUnsaveMessages:(id)arg1 animated:(_Bool)arg2 toSaved:(_Bool)arg3;
//- (void)_saveOrUnsaveMessage:(id)arg1 animated:(_Bool)arg2;
//- (void)_showDeleteFailedMessageActionSheet:(id)arg1;
//- (void)_showSendAndSaveActionSheet:(id)arg1 messageViewModel:(id)arg2;
//- (void)didPressAddToGroupButtonInChatBurger;
//- (void)didRemoveSnapchatter:(id)arg1 conversationId:(id)arg2;
//- (void)didAddSnapchatter:(id)arg1 friendSourceType:(long long)arg2 conversationId:(id)arg3;
//- (void)didSaveMediasToCameraRollFromViewModel:(id)arg1;
//- (void)didBatchSaveOrUnsaveMessageIds:(id)arg1 conversationId:(id)arg2 toSaved:(_Bool)arg3;
//- (void)didSaveOrUnsaveMessageId:(id)arg1 conversationId:(id)arg2;
//- (void)_addCustomStickerForData:(id)arg1;
//- (void)didSaveCustomSticker:(id)arg1;
//- (void)didPressSendToForForwardableViewModel:(id)arg1;
//- (void)actionMenuDidDismiss;
//- (void)actionMenuDidOpen;
//- (id)_messageViewModelForIndexPath:(id)arg1;
//- (_Bool)_hasSendingMessageInBlockForViewModel:(id)arg1 indexPath:(id)arg2;
//- (void)setActionMenuShown:(_Bool)arg1;
//- (void)showActionMenuAtIndexPath:(id)arg1 cell:(id)arg2 selectedIndex:(unsigned long long)arg3 viewModel:(id)arg4 gestureType:(long long)arg5;
//- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
//- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
//- (void)didDismissAlertView;
//- (void)willDisplayAlertView;
//- (long long)sourceViewType;
//- (id)_firstStoryToReplayForFriendStories:(id)arg1 viewLocation:(long long)arg2;
//- (id)_currentFriendStoriesDisplaying;
//- (id)_chatStoryIconUpdaterForViewLocation:(long long)arg1;
//- (void)operaPresenter:(id)arg1 didFinishViewingPlaylistGroupDataModel:(id)arg2 nextGroupDataModel:(id)arg3;
//- (void)operaPresenter:(id)arg1 didBeginPlayingPlaylistGroupDataModel:(id)arg2;
//- (void)operaPresenterDidTearDown:(id)arg1;
//- (void)operaPresenterDidFinishDismissing:(id)arg1;
//- (void)operaPresenterDidFailToPresent:(id)arg1;
//- (void)operaPresenterWillBeginAnimatingToDismiss:(id)arg1;
//- (void)operaPresenterDidCancelDismissing:(id)arg1;
//- (void)operaPresenterWillBeginDismissing:(id)arg1 transitionAnimator:(id)arg2;
//- (void)operaPresenterDidFinishPresenting:(id)arg1 transitionAnimator:(id)arg2;
//- (void)operaPresenterWillBeginPresenting:(id)arg1 transitionAnimator:(id)arg2;
//- (id)storiesReplayManager;
//- (void)_tapToLoadFriendStories:(id)arg1 viewingType:(long long)arg2 viewLocation:(long long)arg3;
//- (void)didTapToViewStoryForFriendStories:(id)arg1 viewingType:(long long)arg2 viewLocation:(long long)arg3;
//- (_Bool)shouldShowChatStoryHeader;
//- (void)leftButtonPressed;
//- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
//- (void)scrollViewWillBeginDragging:(id)arg1;
//- (void)scrollViewDidScroll:(id)arg1;
//- (void)chatDidAttemptToSendMessage;
//- (void)onSnapTapped:(id)arg1 cell:(id)arg2;
//- (void)onPaymentTapped:(id)arg1;
//- (void)attemptRetryBlockForSnap:(id)arg1;
//- (void)attemptRetryBlockForMessage:(id)arg1;
//- (_Bool)onChatTapped:(id)arg1;
//- (void)_saveViewModel:(id)arg1;
//- (void)onCellTapped:(id)arg1 cell:(id)arg2;
//- (double)yOffsetForPaymentView;
//- (void)didSendPayment;
//- (void)didFinishSwipeToSend;
//- (void)didFinishSwipeDown;
//- (void)deleteFailedPaymentMessage:(id)arg1;
//- (void)didUpdateSaveForPaymentMessage:(id)arg1;
//- (void)flowSuccessfullyCompleted;
//- (void)cardLinkingSuccessful;
//- (void)productViewControllerDidFinish:(id)arg1;
//- (void)didTapDeepLinkWithUrl:(id)arg1 additionalInfo:(id)arg2;
//- (void)stackedTableViewCellDidFinishPlayingNoteWithMessageId:(id)arg1;
//- (void)stackedTableViewCell:(id)arg1 didSelectIndex:(unsigned long long)arg2 viewModel:(id)arg3;
//- (void)textTableViewCellDidSelectCashLabelWithCell:(id)arg1;
//- (struct NSDictionary *)conversationStickerUsageHistory;
//- (void)friendmojiAvatarPickerClosedWithFriendmojiType:(long long)arg1 selectedStickerId:(id)arg2;
//- (_Bool)showFriendmojiHintWithTargetView:(id)arg1 delegate:(id)arg2;
//- (void)dismissAvatarPicker;
//- (_Bool)showAvatarPickerWithBitmojiUsers:(id)arg1 targetView:(id)arg2 delegate:(id)arg3;
//- (_Bool)isPartiallyVisible;
//- (_Bool)supports4GCalling;
//- (_Bool)isGroupConversation;
//- (_Bool)isQuickSnapEnabled;
//- (id)replyParameters;
//- (struct CGSize)_chatViewSize;
//- (void)updateChatViewSize;
//- (void)chatInputController:(id)arg1 inputTextHeightDidChangeAnimated:(_Bool)arg2;
//- (void)drawerInactiveButVisible:(_Bool)arg1;
//- (void)drawerActive;
//- (void)resizePreview:(_Bool)arg1 dueToTextInput:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
//- (_Bool)isEligibleSenderReceiverPair;
//- (void)_presentSwipeToSend;
//- (void)handleSendCashActionInitiatedWithSwipe:(_Bool)arg1;
//- (void)chatInputController:(id)arg1 didTapSendPaymentText:(id)arg2 cashTagRanges:(id)arg3 amount:(unsigned long long)arg4;
//- (void)chatInputControllerCashSendButtonPressed:(id)arg1;
//- (void)chatInputControllerViewDidChange:(id)arg1;
//- (void)chatInputControllerTextDidChange:(id)arg1;
//- (void)chatInputController:(id)arg1 didTypingStateChange:(long long)arg2;
//- (void)chatInputController:(id)arg1 didPasteGifData:(id)arg2;
//- (void)chatInputController:(id)arg1 didTapSendText:(id)arg2;
//- (id)chatInputControllerRecipient:(id)arg1;
//- (_Bool)paymentSwipeSenderVisible;
//- (void)restoreViewAfterSideMenuDisappear;
//- (void)prepareSideMenuAppear;
//- (void)setSideMenuHidden:(_Bool)arg1;
//- (void)gotoSendMeSnapsSettingsViewWithAnimation:(_Bool)arg1;
//- (void)goRightWithAnimation:(_Bool)arg1;
//- (id)chatMessages;
//- (_Bool)doNotDisturb;
//- (id)chatRecipientUsername;
//- (_Bool)_isPlayingMedia;
//- (void)_playChatSoundMaybe:(unsigned long long)arg1;
//- (void)_playChatSentSoundMaybe;
//- (void)_playChatReceivedSoundMaybe;
//- (void)_addCustomVolumeIgnoringNextVolumeChange:(_Bool)arg1;
//- (void)_removeCustomVolume;
//- (void)dismissFullScreenView;
//- (id)userSession;
//- (void)updateTableContentInsetForPresenceWithHeight:(double)arg1;
//- (_Bool)isTheUserConsumingMedia;
//- (_Bool)isTextLengthBlockingPreview;
//- (id)myUsername;
//- (_Bool)isFullScreenMode;
//- (void)setIsFullScreenMode:(_Bool)arg1;
//- (_Bool)inputViewTransparent;
//- (void)setInputViewTransparent:(_Bool)arg1;
//- (_Bool)keyboardHidden;
//- (void)setKeyboardHidden:(_Bool)arg1;
//- (_Bool)inputAccessoriesHidden;
//- (void)setInputAccessoriesHidden:(_Bool)arg1;
//- (void)panInputAccessoriesWithGestureRecognizer:(id)arg1 dragToHide:(_Bool)arg2;
//- (void)detectTouchViewDidDetectTouch:(id)arg1;
//- (void)dismissTooltipIfNeeded;
//- (void)showTooltip;
//- (void)showTooltipIfNeeded;
//- (id)_bubbleChatController;
//- (void)unlockScrollWithRequestId:(id)arg1;
//- (void)lockScrollWithRequestId:(id)arg1;
//- (void)videoPreviewWillGoFullscreen;
//- (void)outgoingCardDidHide;
//- (void)outgoindCardWillBeShown;
//- (void)cancelAudioVideoNoteMaybeWithCompletion:(CDUnknownBlockType)arg1;
//- (id)getInputView;
//- (id)getContainerView;
//- (void)presenceBarInitialized:(id)arg1;
//- (id)_snapChatTableViewCell:(id)arg1;
//- (void)longPressBeganForCellWithSnap:(id)arg1 cell:(id)arg2;
//- (_Bool)snapCellShouldHandleLongPressForSnap:(id)arg1;
//- (void)handleLongPressForCellWithBaseMessage:(id)arg1 messageViewModel:(id)arg2;
//- (void)handleLongPressForMessage:(id)arg1 messageViewModel:(id)arg2 cell:(id)arg3;
//- (void)didLongPressOnMessageViewModel:(id)arg1 cell:(id)arg2;
//- (void)didTapWhitespaceForStackedCell:(id)arg1 indexPath:(id)arg2 viewModel:(id)arg3;
//- (void)didLongPressOnCell:(id)arg1 indexPath:(id)arg2 selectedIndex:(unsigned long long)arg3 viewModel:(id)arg4 gestureRecognizer:(id)arg5;
//- (void)_onFailureCameraRollSave;
//- (void)_onSuccessCameraRollSaveWithMessage:(id)arg1 chatSendHelper:(id)arg2;
//- (void)_saveToCameraRollForSavableViewModel:(id)arg1;
//- (void)showSaveOptionsForSavableViewModel:(id)arg1 cell:(id)arg2;
//- (void)handleLongPress:(id)arg1 forStackedViewModel:(id)arg2;
//- (void)pan:(id)arg1;
//- (_Bool)_isPlayingSearchShare;
//- (_Bool)_isPlayingNYCShare;
//- (_Bool)_isPlayingStoryShare;
//- (_Bool)isPlayingSnap;
//- (id)chatInputController;
//- (id)conversationId;
//- (_Bool)canBeShown;
//- (_Bool)shouldDisableScrollOut:(id)arg1;
//- (_Bool)shouldShowGreetingSticker;
//- (void)viewDidPopFromStack;
//- (void)viewDidSwipeOut;
//- (void)viewDidSwipeIn;
//- (void)viewDidFullyDisappearFromStack:(_Bool)arg1;
//- (void)viewDidFullyAppearFromStack:(_Bool)arg1;
//- (void)viewDidAppearAtOffset:(double)arg1;
//- (void)releaseMemory;
//- (void)viewWillEnterBackground;
//- (void)viewDidBecomeActive;
//- (void)viewWillResignActive;
//- (_Bool)shouldPopToRootViewController;
//- (id)additionalS2RDebugOutput;
//- (void)dealloc;
//- (void)prepareToBeVisible;
//- (void)viewDidAppear:(_Bool)arg1;
//- (void)viewDidLoad;
//- (void)_initCashController;
//- (void)_initAutoResponderController;
//- (void)_initMessageReleaser;
//- (void)_initGestures;
//- (void)layoutChatTableViewIfNeeded;
//- (void)_initHeader;
//- (void)_initChatTable;
//- (void)_initLogger;
//- (void)loadView;
//- (id)initWithUserSession:(id)arg1 parentDelegate:(id)arg2;
//- (id)getPageName;
//- (id)getPageViewName;
//
//// Remaining properties
//@property(readonly, copy) NSString *debugDescription;
//@property(readonly, copy) NSString *description;
//@property(readonly) unsigned long long hash;
//@property(readonly) Class superclass;

@end

