//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2017 17:44:06).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIKit.h>
#import "SCSnapPlayController.h"

//#import "EGORefreshTableHeaderDelegate-Protocol.h"
//#import "SCAnimatedFeedBackgroundViewAnimationDelegate-Protocol.h"
//#import "SCBaseMediaOperaPresenterDelegate-Protocol.h"
//#import "SCBlockedExceptionAlertControllerDelegate-Protocol.h"
//#import "SCCardController-Protocol.h"
//#import "SCCardStyling-Protocol.h"
//#import "SCDeepLinkMiniProfileControllerDelegate-Protocol.h"
//#import "SCDeepLinkableViewSource-Protocol.h"
//#import "SCFeedCellPanningStateDelegate-Protocol.h"
//#import "SCFeedDataSourceDelegate-Protocol.h"
//#import "SCFeedGestureDelegate-Protocol.h"
//#import "SCFeedPage-Protocol.h"
//#import "SCFeedTableFooterViewDelegate-Protocol.h"
//#import "SCFeedTableHeaderControllerDelegate-Protocol.h"
//#import "SCFeedToChatTapDetectionViewDelegate-Protocol.h"
//#import "SCGroupMiniProfileViewControllerDelegate-Protocol.h"
//#import "SCMiniProfileViewControllerDelegate-Protocol.h"
//#import "SCOverscrollableController-Protocol.h"
//#import "SCPullToDismissControllerGestureDelegate-Protocol.h"
//#import "SCPullToRefreshViewDelegate-Protocol.h"
//#import "SCQuickAddControllerDataSrouce-Protocol.h"
//#import "SCQuickAddControllerDelegate-Protocol.h"
//#import "SCShakeToReportDelegate-Protocol.h"
//#import "SCSnapPlayContainer-Protocol.h"
//#import "SCSnapPlayDelegate-Protocol.h"
//#import "SCTimeProfilable-Protocol.h"
//#import "SKStoreProductViewControllerDelegate-Protocol.h"
//#import "SendSnapNavigationControllerDelegate-Protocol.h"
//#import "SwipeView-Protocol.h"
//#import "UIGestureRecognizerDelegate-Protocol.h"
//#import "UINavigationControllerDelegate-Protocol.h"
//#import "UITableViewDataSource-Protocol.h"
//#import "UITableViewDelegate-Protocol.h"
//
//@class EGORefreshTableHeaderView, NSMutableSet, NSString, SCAnimatedFeedBackgroundView, SCAppNotification, SCBaseMediaOperaPresenter, SCBlockedExceptionAlertViewController, SCCardContainerView, SCCardGradientView, SCChatMainViewController, SCDeepLinkMiniProfileController, SCFeedCellPanningState, SCFeedTableFooterView, SCFeedTableHeaderController, SCFeedTableViewCell, SCFeedVerticalPresenter, SCFriendLongPressGestureRecognizer, SCFriendsFeedChatActionHandler, SCGradientView, SCGroupMiniProfileViewController, SCMiniProfileViewController, SCPullToRefreshBackgroundRenderView, SCPullToRefreshView, SCQuickAddController, SCSnapPlayController, SCStopwatch, SCUpgradeVersionView, SCUserSession, UIImageView, UILabel, UITableView, UITapGestureRecognizer, UIView;
//@protocol NavigationDelegate, SCFeedDataSource, SCHovaOverscrollDelegate, SCReplyDelegate, SCStartChatDelegate, SCSwipeViewParentDelegate, SCViewingMediaDelegate, SendSnapNavigationControllerDelegate;

@interface SCFeedViewController : UIViewController
//<EGORefreshTableHeaderDelegate, SCTimeProfilable, UITableViewDataSource, UITableViewDelegate, UIGestureRecognizerDelegate, SCFeedDataSourceDelegate, SCFeedTableHeaderControllerDelegate, SCAnimatedFeedBackgroundViewAnimationDelegate, SCFeedGestureDelegate, SKStoreProductViewControllerDelegate, SCPullToDismissControllerGestureDelegate, SCSnapPlayDelegate, SCBlockedExceptionAlertControllerDelegate, SCSnapPlayContainer, SCFeedToChatTapDetectionViewDelegate, SCPullToRefreshViewDelegate, SCCardController, SCFeedTableFooterViewDelegate, SCQuickAddControllerDelegate, UINavigationControllerDelegate, SCBaseMediaOperaPresenterDelegate, SCFeedCellPanningStateDelegate, SCQuickAddControllerDataSrouce, SCDeepLinkMiniProfileControllerDelegate, SCMiniProfileViewControllerDelegate, SCGroupMiniProfileViewControllerDelegate, SCShakeToReportDelegate, SwipeView, SCCardStyling, SCOverscrollableController, SendSnapNavigationControllerDelegate, SCDeepLinkableViewSource, SCFeedPage>
//{
//    SCMiniProfileViewController *_miniProfileViewController;
//    SCGroupMiniProfileViewController *_groupMiniProfileViewController;
//    SCUserSession *_userSession;
//    NSString *_tapToChatRecipient;
//    long long _tapToChatReplyType;
//    _Bool _isTapToChatReplyFromMischief;
//    long long _tapToChatCellViewPosition;
//    SCFeedTableFooterView *_tableFooterView;
//    SCFeedTableHeaderController *_tableHeaderController;
//    SCQuickAddController *_quickAddController;
//    _Bool _cachedShouldShowQuickAdd;
//    SCFeedVerticalPresenter *_verticalPresenter;
//    SCBaseMediaOperaPresenter *_operaPresenter;
//    NSString *_lastPlayedSnapIdentifier;
//    SCFeedCellPanningState *_panningState;
//    SCFeedTableViewCell *_cachedFeedCell;
//    SCBlockedExceptionAlertViewController *_blockedExceptionAlertVC;
//    SCDeepLinkMiniProfileController *_deepLinkMiniProfileController;
//    SCStopwatch *_feedLoadingViewTimer;
//    _Bool _deferAllSystemEdgeGestures;
//    _Bool _shouldDisableScrollToTop;
//    UIView *_blueOverlay;
//    NSMutableSet *_displayedItems;
//    NSString *_lastLoggedSnapId;
//    SCFriendsFeedChatActionHandler *_friendsFeedChatActionHandler;
//    _Bool _didEnterThroughHova;
//    _Bool _viewHasFullyAppearedAtLeastOnce;
//    _Bool _phoneVerificationHeaderPromptExists;
//    _Bool _animationInProgress;
//    _Bool _reloading;
//    _Bool _firstFetchUpdatesRequest;
//    _Bool _didLogFirstChatReadyToView;
//    _Bool _delayedReloadTableView;
//    _Bool _cellSwiping;
//    _Bool _viewHasAppeared;
//    SCChatMainViewController *_chatVC;
//    id <SCHovaOverscrollDelegate> _hovaOverscrollDelegate;
//    SCAppNotification *_sourceNotification;
//    id <SCViewingMediaDelegate> _delegate;
//    id <SCSwipeViewParentDelegate> _parentDelegate;
//    id <SCReplyDelegate> _replyDelegate;
//    id <SCStartChatDelegate> _startChatDelegate;
//    id <SendSnapNavigationControllerDelegate> _sendSnapNavigationControllerDelegate;
//    id <NavigationDelegate> _navigationDelegate;
//    UITableView *_tableView;
//    UILabel *_emptyFeedListPlaceholder;
//    id <SCFeedDataSource> _dataSource;
//    UITapGestureRecognizer *_tapGestureRecognizer;
//    UITapGestureRecognizer *_delayedTapGestureRecognizer;
//    SCFriendLongPressGestureRecognizer *_longPressGestureRecognizer;
//    UITapGestureRecognizer *_doubleTapGestureRecognizer;
//    SCSnapPlayController *_snapPlayController;
//    SCAnimatedFeedBackgroundView *_animatedBackgroundView;
//    EGORefreshTableHeaderView *_refreshHeaderView;
//    SCPullToRefreshBackgroundRenderView *_refreshBackgroundRenderView;
//    SCPullToRefreshView *_cardRefreshHeaderView;
//    SCUpgradeVersionView *_upgradeHeader;
//    UIImageView *_topGradientView;
//    SCGradientView *_bottomGradientView;
//    double _lastScrolledYOffset;
//    double _lastYOffsetBeforeScrolling;
//    NSString *_viewingSnapCellIdentifier;
//    NSString *_selectedUsername;
//    SCCardContainerView *_cardContainerView;
//}
//
//+ (int)context;
//+ (id)pageViewName;
//@property(retain, nonatomic) SCCardContainerView *cardContainerView; // @synthesize cardContainerView=_cardContainerView;
//@property(copy, nonatomic) NSString *selectedUsername; // @synthesize selectedUsername=_selectedUsername;
//@property(copy, nonatomic) NSString *viewingSnapCellIdentifier; // @synthesize viewingSnapCellIdentifier=_viewingSnapCellIdentifier;
//@property(nonatomic) _Bool viewHasAppeared; // @synthesize viewHasAppeared=_viewHasAppeared;
//@property(nonatomic) _Bool cellSwiping; // @synthesize cellSwiping=_cellSwiping;
//@property(nonatomic) _Bool delayedReloadTableView; // @synthesize delayedReloadTableView=_delayedReloadTableView;
//@property(nonatomic) double lastYOffsetBeforeScrolling; // @synthesize lastYOffsetBeforeScrolling=_lastYOffsetBeforeScrolling;
//@property(nonatomic) double lastScrolledYOffset; // @synthesize lastScrolledYOffset=_lastScrolledYOffset;
//@property(retain, nonatomic) SCGradientView *bottomGradientView; // @synthesize bottomGradientView=_bottomGradientView;
//@property(retain, nonatomic) UIImageView *topGradientView; // @synthesize topGradientView=_topGradientView;
//@property(nonatomic) _Bool didLogFirstChatReadyToView; // @synthesize didLogFirstChatReadyToView=_didLogFirstChatReadyToView;
//@property(nonatomic) _Bool firstFetchUpdatesRequest; // @synthesize firstFetchUpdatesRequest=_firstFetchUpdatesRequest;
//@property(retain, nonatomic) SCUpgradeVersionView *upgradeHeader; // @synthesize upgradeHeader=_upgradeHeader;
//@property(retain, nonatomic) SCPullToRefreshView *cardRefreshHeaderView; // @synthesize cardRefreshHeaderView=_cardRefreshHeaderView;
//@property(retain, nonatomic) SCPullToRefreshBackgroundRenderView *refreshBackgroundRenderView; // @synthesize refreshBackgroundRenderView=_refreshBackgroundRenderView;
//@property(retain, nonatomic) EGORefreshTableHeaderView *refreshHeaderView; // @synthesize refreshHeaderView=_refreshHeaderView;
//@property(nonatomic) _Bool reloading; // @synthesize reloading=_reloading;
//@property(nonatomic) _Bool animationInProgress; // @synthesize animationInProgress=_animationInProgress;
//@property(retain, nonatomic) SCAnimatedFeedBackgroundView *animatedBackgroundView; // @synthesize animatedBackgroundView=_animatedBackgroundView;
@property(retain, nonatomic) SCSnapPlayController *snapPlayController; // @synthesize snapPlayController=_snapPlayController;
//@property(retain, nonatomic) UITapGestureRecognizer *doubleTapGestureRecognizer; // @synthesize doubleTapGestureRecognizer=_doubleTapGestureRecognizer;
//@property(retain, nonatomic) SCFriendLongPressGestureRecognizer *longPressGestureRecognizer; // @synthesize longPressGestureRecognizer=_longPressGestureRecognizer;
//@property(retain, nonatomic) UITapGestureRecognizer *delayedTapGestureRecognizer; // @synthesize delayedTapGestureRecognizer=_delayedTapGestureRecognizer;
//@property(retain, nonatomic) UITapGestureRecognizer *tapGestureRecognizer; // @synthesize tapGestureRecognizer=_tapGestureRecognizer;
//@property(retain, nonatomic) id <SCFeedDataSource> dataSource; // @synthesize dataSource=_dataSource;
//@property(retain, nonatomic) UILabel *emptyFeedListPlaceholder; // @synthesize emptyFeedListPlaceholder=_emptyFeedListPlaceholder;
//@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
//@property(readonly, nonatomic) _Bool phoneVerificationHeaderPromptExists; // @synthesize phoneVerificationHeaderPromptExists=_phoneVerificationHeaderPromptExists;
//@property(readonly, nonatomic) _Bool viewHasFullyAppearedAtLeastOnce; // @synthesize viewHasFullyAppearedAtLeastOnce=_viewHasFullyAppearedAtLeastOnce;
//@property(nonatomic) __weak id <NavigationDelegate> navigationDelegate; // @synthesize navigationDelegate=_navigationDelegate;
//@property(nonatomic) __weak id <SendSnapNavigationControllerDelegate> sendSnapNavigationControllerDelegate; // @synthesize sendSnapNavigationControllerDelegate=_sendSnapNavigationControllerDelegate;
//@property(nonatomic) __weak id <SCStartChatDelegate> startChatDelegate; // @synthesize startChatDelegate=_startChatDelegate;
//@property(nonatomic) __weak id <SCReplyDelegate> replyDelegate; // @synthesize replyDelegate=_replyDelegate;
//@property(nonatomic) __weak id <SCSwipeViewParentDelegate> parentDelegate; // @synthesize parentDelegate=_parentDelegate;
//@property(nonatomic) __weak id <SCViewingMediaDelegate> delegate; // @synthesize delegate=_delegate;
//@property(nonatomic) _Bool didEnterThroughHova; // @synthesize didEnterThroughHova=_didEnterThroughHova;
//@property(retain, nonatomic) SCAppNotification *sourceNotification; // @synthesize sourceNotification=_sourceNotification;
//@property(nonatomic) __weak id <SCHovaOverscrollDelegate> hovaOverscrollDelegate; // @synthesize hovaOverscrollDelegate=_hovaOverscrollDelegate;
//@property(nonatomic) __weak SCChatMainViewController *chatVC; // @synthesize chatVC=_chatVC;
//- (void).cxx_destruct;
- (id)getSnapPlayControllerInCurrentVC;
//- (_Bool)shouldCensorScreenshot;
//- (id)viewControllerToQueryForPolicy;
//- (void)dismissFullScreenMedia;
//- (_Bool)isFirstFeedCellVisible;
//- (id)additionalS2RDebugOutput;
//- (void)didDismissMiniProfile:(id)arg1;
//- (id)deepLinkableViewController:(id)arg1 additionalInfo:(id)arg2;
//- (_Bool)shouldPopToRootViewController;
//- (unsigned long long)sc_tabBarItemPosition;
//- (id)sc_swipeTransitionBlurEffect;
//- (id)sc_swipeTransitionGradientColors;
//- (void)didSelectProfileButton:(id)arg1;
//- (id)sc_tabBarItem;
//- (id)sc_navigationItem;
//- (void)preparePanningStateWithIdentifier:(id)arg1;
//- (void)didGrantBlockExceptionForGroup:(id)arg1;
//- (void)cellPresentAlertView:(id)arg1;
//- (_Bool)cellShouldPresentAlertView:(id)arg1;
//- (void)overscrollWithContentOffset:(double)arg1 overscrollPercent:(double)arg2;
//- (void)pannableCellViewVisiblityDidChange:(double)arg1 tracking:(_Bool)arg2;
//- (_Bool)attemptToScrollToPannableCellAtLocation:(struct CGPoint)arg1 withVelocity:(struct CGPoint)arg2;
//- (void)feedCellPanningState:(id)arg1 didEndPanningWithIdentifier:(id)arg2;
//- (void)loadMoreConversationsIfPossibleForceOnFailed:(_Bool)arg1;
//- (void)tableFooterDidChange;
//- (void)showMyContactsVC:(_Bool)arg1 skipPhoneVerification:(_Bool)arg2 fromPXPrompt:(_Bool)arg3;
//- (void)showMyContactsVC:(_Bool)arg1 skipPhoneVerification:(_Bool)arg2;
//- (void)tableHeaderDidChange;
//- (void)didShowPhoneVerificationView;
//- (void)didTapOnFeedToChatTapDetectionView;
//- (void)updateEmptyFeedPlaceHolderWithSearchStatus:(_Bool)arg1;
//- (long long)_getAddSourceTypeForFriend:(id)arg1;
//- (void)miniProfileViewControllerWasDismissed:(id)arg1;
//- (void)miniProfileViewControllerDidPressSnapButton:(id)arg1;
//- (void)miniProfileController:(id)arg1 wantsToNavigateToChatWithDeepLinkURL:(id)arg2;
//- (id)presentingVC;
//- (void)updateLastPlayedSnapIdentifierWithViewModel:(id)arg1;
//- (void)didChangePullToDismissWithPercentage:(double)arg1;
//- (void)resetViewingCellAnimated:(_Bool)arg1;
//- (id)viewingSnapCell;
//- (_Bool)shouldShowNotificationInCurrentMediaState;
//- (long long)sourceViewType;
//- (void)setVisibleCellsUserInteractionEnabled:(_Bool)arg1 excludedCell:(id)arg2;
//- (void)cellHandleStoryIconPressed:(id)arg1;
//- (void)_moveToCameraFromFeedCell:(id)arg1;
//- (void)cellHandleSnapButtonPressed:(id)arg1;
//- (void)cellHandleReplyButtonPressed:(id)arg1;
//- (void)_cellHandleTapToViewChatCards:(id)arg1;
//- (void)handleTimerExiprationOnSnap:(id)arg1 cell:(id)arg2;
//- (void)handleTimerExpirationOnGroupSnap:(id)arg1;
//- (void)_cellHandleTapOnUnopenedReceivedGroupSnap:(id)arg1;
//- (void)_prepareMediaForMessageCompletionHelperWithCell:(id)arg1 messageId:(id)arg2 conversationId:(id)arg3 isMessageReadyToDisplay:(_Bool)arg4 isSnapEvent:(_Bool)arg5;
//- (void)cellHandleTapOnUnopenedReceivedMedia:(id)arg1;
//- (void)handleTapOnSnap:(id)arg1 cell:(id)arg2;
//- (void)handleLongPressOnSnap:(id)arg1 cell:(id)arg2;
//- (void)cellPresentMiniProfile:(id)arg1;
//- (void)_cellPresentMischiefMiniProfile:(id)arg1;
//- (void)cellPresentUnifiedMiniProfile:(id)arg1;
//- (void)cell:(id)arg1 attachFeedToChatTapDetectionViewWithLocationInCell:(struct CGPoint)arg2;
//- (void)cellHandleDoubleTapOnChat:(id)arg1;
//- (void)cellHandleDebugButtonPressed:(id)arg1 withFeedItem:(id)arg2;
//- (void)prepareNextVCWithViewModel:(id)arg1 atRow:(unsigned long long)arg2 shouldDisplayChatCards:(_Bool)arg3;
//- (unsigned long long)rowForCell:(id)arg1;
//- (void)cellHandleTapOnChat:(id)arg1;
//- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
//- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
//- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
//- (void)cancelTapGestureRecognizers;
//- (id)cellAtPoint:(struct CGPoint)arg1;
//- (void)_presentMiniProfileForFriend:(id)arg1 addSource:(long long)arg2 cellViewPosition:(long long)arg3;
//- (void)_showProfileViewOnQuickAddCellOnLongPress:(id)arg1 gestureRecognizer:(id)arg2;
//- (void)_showProfileViewOnQuickAddCellOnTap:(id)arg1 gestureRecognizer:(id)arg2;
//- (void)handleLongPress:(id)arg1;
//- (void)handleDelayedTap:(id)arg1;
//- (void)handleDoubleTap:(id)arg1;
//- (void)handleTap:(id)arg1;
//- (void)updateUpgradeHeaderIfNecessary;
//- (void)pullToRefreshDidFinish:(id)arg1;
//- (void)didFinishFetchUpdates:(id)arg1;
//- (void)pullToRefresh:(id)arg1 percentPulledDidChange:(double)arg2;
//- (void)pullToRefresh:(id)arg1 refreshStateDidChange:(long long)arg2;
//- (_Bool)pullToRefreshIsDataSourceLoading:(id)arg1;
//- (_Bool)pullToRefreshShouldRefresh:(id)arg1;
//- (_Bool)egoRefreshTableHeaderDataSourceIsLoading:(id)arg1;
//- (void)egoRefreshTableHeaderDidTriggerRefresh:(id)arg1;
//- (void)didPullToRefresh;
//- (void)feedBackgroundAnimationDidStop;
//- (void)feedBackgroundAnimationDidStart;
//- (void)didSendSnaps:(id)arg1;
//- (void)didCancelFromPreview:(id)arg1;
//- (void)quickAddController:(id)arg1 didDisplayProfilePictureOnCellView:(id)arg2 onThumbnail:(id)arg3 friend:(id)arg4;
//- (void)quickAddController:(id)arg1 didFinishFriendAction:(id)arg2;
//- (id)quickAddControllerParentViewController;
//- (id)sendSnapNavigationControllerDelegateForQuickAddController;
//- (id)replyParametersForName:(id)arg1;
//- (void)loadMoreFeedItemsIfCloseToLoadingView;
//- (void)_updateTableFooterView;
//- (id)_feedCellForConversationId:(id)arg1;
//- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
//- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
//- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
//- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
//- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
//- (_Bool)showBottomBorderForIndexPath:(id)arg1;
//- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
//- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
//- (long long)numberOfSectionsInTableView:(id)arg1;
//- (_Bool)shouldShowQuickAdd;
//- (void)showCameraForUsername:(id)arg1 pageSource:(long long)arg2 context:(id)arg3 replyType:(long long)arg4 isMischief:(_Bool)arg5 cellViewPosition:(long long)arg6;
//- (void)showCameraFromDoubleTapToReplyWithRecipient:(id)arg1 replyType:(long long)arg2 isMischief:(_Bool)arg3 cellViewPosition:(long long)arg4;
//- (_Bool)shouldTriggerPullToDismissWithSwipeDirection:(unsigned long long)arg1;
//- (struct CGRect)iconViewRectAtCell:(id)arg1;
//- (struct CGRect)iconViewRectForUsername:(id)arg1;
//- (id)feedCellForIdentifier:(id)arg1;
//- (void)groupMiniProfileControllerWasDismissed:(id)arg1;
//- (void)groupMiniProfileController:(id)arg1 wantsToNavigateToChatForFriend:(id)arg2 deepLinkURL:(id)arg3;
//- (void)groupMiniProfileControllerDidPressSnapButton:(id)arg1;
//- (void)groupMiniProfileControllerDidPressChatButton:(id)arg1;
//- (void)groupMiniProfileControllerDidUpdateGroup:(id)arg1;
//- (void)_logSnapLoaded:(id)arg1;
//- (void)navigateToChatViewWithFriend:(id)arg1 deepLinkURL:(id)arg2 viewController:(id)arg3;
//- (_Bool)shouldDelayUpdateTableView;
//- (_Bool)shouldStopViewModelUpdates;
//- (void)prepareToReloadTableViewWithLogPrefix:(id)arg1;
//- (void)reloadTableView;
//- (void)didCompleteSyncWithServer;
//- (void)reloadTableViewIfNecessary;
//- (void)reloadTableViewCellAtRow:(long long)arg1;
//- (void)didFetchViewModels:(id)arg1;
//- (void)_setPreferredScreenEdgesDeferringSystemGesturesToAll:(_Bool)arg1;
//- (unsigned long long)preferredScreenEdgesDeferringSystemGestures;
//- (long long)preferredStatusBarStyle;
//- (void)handleViewHasAppearedIfNecessary;
//- (void)tabBarTriggeredWithAction:(long long)arg1;
//- (void)_scrollToFirstConsumableContentCell;
//- (void)_logSCAFriendFeedCell:(id)arg1;
//- (void)_updateFeedItemImpression;
//- (void)_updateDisplayedItems;
//- (void)viewDidFullyDisappear;
//- (void)viewDidPartiallyDisappear;
//- (void)viewDidFullyAppear;
//- (void)viewDidPartiallyAppear;
//- (void)viewCanAppear;
//- (void)viewDidDisappear:(_Bool)arg1;
//- (void)applicationDidEnterBackground:(id)arg1;
//- (void)didBecomeActive;
//- (void)deallocGestureRecognizers;
//- (void)dealloc;
//- (void)viewDidLoad;
//- (void)updateEmptyFeedListPlaceHolderLabelVisibility;
//- (void)updateEmptyFeedListPlaceHolderLabelFrame;
//- (void)updateFooterLoadingViewVisibility;
//- (void)updateFooterAddContactsVisibility;
//- (void)statusBarTapped;
//- (void)scrollToTop:(_Bool)arg1;
//- (void)scrollViewDidEndScrolling:(id)arg1;
//- (void)scrollViewDidEndDecelerating:(id)arg1;
//- (void)scrollViewWillBeginDragging:(id)arg1;
//- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
//- (void)scrollViewDidScroll:(id)arg1;
//- (void)baseMediaOperaPresenter:(id)arg1 resumedTimerForMessage:(id)arg2;
//- (void)baseMediaOperaPresenter:(id)arg1 pausedTimerForMessage:(id)arg2;
//- (void)baseMediaOperaPresenter:(id)arg1 didTapReportForMessage:(id)arg2 shareableMediaComponents:(id)arg3;
//- (void)baseMediaOperaPresenter:(id)arg1 didTapSendForMessage:(id)arg2;
//- (void)operaPresenterDidDisappear;
//- (void)operaPresenterWillAppear;
//- (void)baseMediaOperaPresenter:(id)arg1 didTapFooterBarForMedia:(id)arg2;
//- (id)baseMediaOperaPresenter:(id)arg1 thumbnailViewForMedia:(id)arg2 conversationId:(id)arg3;
//- (void)lazyLoadIfViewDidFullyAppearForTheFirstTime;
//- (void)pushStartChatView;
//- (id)operaPresenter;
//- (void)setUpSnapPlayController;
//- (_Bool)isPlayingSnapOrStory;
//- (_Bool)isPlayingStory;
//- (_Bool)isPlayingSnap;
//- (id)quickAddController;
//- (void)_preloadChatViewImageAssetsOnce;
//- (void)initGestureRecognizers;
//- (void)initTableFooterView;
//- (void)initTableHeaderView;
//- (void)initBlueOverlay;
//- (void)initGradientView;
//- (void)initTableView;
//- (void)loadView;
//- (id)initWithUserSession:(id)arg1;
//- (id)getPageName;
//- (id)getPageViewName;
//
//// Remaining properties
//@property(retain, nonatomic) SCCardGradientView *cardGradientView;
//@property(readonly, copy) NSString *debugDescription;
//@property(readonly, copy) NSString *description;
//@property(readonly) unsigned long long hash;
//@property(readonly) Class superclass;

@end

