//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2017 17:44:06).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCGeofencedObject.h"

//@class NSArray, NSDate, NSDictionary, NSNumber, NSSet, NSString, NSURL;
//SCGeoFilterLoadingMetaData, SCSponsoredSlug, SOJUUnlockableTrackInfo;

@interface SCGeoFilter : SCGeofencedObject
{
    _Bool _isSponsored;
    _Bool _isFrameFilter;
    _Bool _belowDrawingLayer;
    _Bool _isAnimated;
    _Bool _isPrecached;
    _Bool _guaranteedDelivery;
    _Bool _isMenuFilter;
    _Bool _eligibleForNotification;
    NSDate *_expirationDate;
    double _assetTTL;
    long long _eligibility;
    NSString *_filterId;
    long long _unlockableContentType;
    long long _priority;
    long long _scaleSetting;
    unsigned long long _positionSetting;
    unsigned long long _targetingType;
//    SCSponsoredSlug *_sponsoredSlug;
//    SCGeoFilterLoadingMetaData *_loadingMetaData;
    NSString *_encryptedGeoData;
    NSURL *_imageURL;
    NSDictionary *_imageURLParams;
    long long _autoStacking;
    NSDictionary *_unlockableContexts;
    NSArray *_unlockableAttributes;
    NSString *_unlockableCategory;
    long long _autoRefreshDelayInMilliseconds;
    NSString *_dynamicFilterRefreshHint;
    NSString *_dynamicFilterUpdatingMessage;
    NSString *_unlockImageLink;
    NSDictionary *_filterPrompt;
    NSNumber *_filterScore;
    NSSet *_exclusionTags;
    NSSet *_excludedByTags;
    NSArray *_scheduleIntervals;
//    SOJUUnlockableTrackInfo *_unlockableTrackInfo;
    NSDictionary *_dynamicContextProperties;
    struct CGPoint _autoRefreshLabelPosition;
}

+ (id)geoFilterWithDictionary:(id)arg1 isPreCached:(_Bool)arg2;
+ (_Bool)isSecondFilterPreferred:(id)arg1 secondFilter:(id)arg2;
@property(readonly, copy, nonatomic) NSDictionary *dynamicContextProperties; // @synthesize dynamicContextProperties=_dynamicContextProperties;
@property(readonly, nonatomic) _Bool eligibleForNotification; // @synthesize eligibleForNotification=_eligibleForNotification;
//@property(readonly, copy, nonatomic) SOJUUnlockableTrackInfo *unlockableTrackInfo; // @synthesize unlockableTrackInfo=_unlockableTrackInfo;
@property(readonly, nonatomic) _Bool isMenuFilter; // @synthesize isMenuFilter=_isMenuFilter;
@property(readonly, copy, nonatomic) NSArray *scheduleIntervals; // @synthesize scheduleIntervals=_scheduleIntervals;
@property(readonly, copy, nonatomic) NSSet *excludedByTags; // @synthesize excludedByTags=_excludedByTags;
@property(readonly, copy, nonatomic) NSSet *exclusionTags; // @synthesize exclusionTags=_exclusionTags;
@property(readonly, nonatomic) _Bool guaranteedDelivery; // @synthesize guaranteedDelivery=_guaranteedDelivery;
@property(readonly, copy, nonatomic) NSNumber *filterScore; // @synthesize filterScore=_filterScore;
@property(readonly, copy, nonatomic) NSDictionary *filterPrompt; // @synthesize filterPrompt=_filterPrompt;
@property(copy, nonatomic) NSString *unlockImageLink; // @synthesize unlockImageLink=_unlockImageLink;
@property(readonly, copy, nonatomic) NSString *dynamicFilterUpdatingMessage; // @synthesize dynamicFilterUpdatingMessage=_dynamicFilterUpdatingMessage;
@property(readonly, copy, nonatomic) NSString *dynamicFilterRefreshHint; // @synthesize dynamicFilterRefreshHint=_dynamicFilterRefreshHint;
@property(readonly, nonatomic) struct CGPoint autoRefreshLabelPosition; // @synthesize autoRefreshLabelPosition=_autoRefreshLabelPosition;
@property(readonly, nonatomic) long long autoRefreshDelayInMilliseconds; // @synthesize autoRefreshDelayInMilliseconds=_autoRefreshDelayInMilliseconds;
@property(copy, nonatomic) NSString *unlockableCategory; // @synthesize unlockableCategory=_unlockableCategory;
@property(copy, nonatomic) NSArray *unlockableAttributes; // @synthesize unlockableAttributes=_unlockableAttributes;
@property(retain, nonatomic) NSDictionary *unlockableContexts; // @synthesize unlockableContexts=_unlockableContexts;
@property(readonly, nonatomic) long long autoStacking; // @synthesize autoStacking=_autoStacking;
@property(readonly, nonatomic) _Bool isPrecached; // @synthesize isPrecached=_isPrecached;
@property(readonly, copy, nonatomic) NSDictionary *imageURLParams; // @synthesize imageURLParams=_imageURLParams;
@property(readonly, copy, nonatomic) NSURL *imageURL; // @synthesize imageURL=_imageURL;
@property(readonly, copy, nonatomic) NSString *encryptedGeoData; // @synthesize encryptedGeoData=_encryptedGeoData;
@property(readonly, nonatomic) _Bool isAnimated; // @synthesize isAnimated=_isAnimated;
@property(readonly, nonatomic, getter=isBelowDrawingLayer) _Bool belowDrawingLayer; // @synthesize belowDrawingLayer=_belowDrawingLayer;
//@property(readonly, nonatomic) SCGeoFilterLoadingMetaData *loadingMetaData; // @synthesize loadingMetaData=_loadingMetaData;
//@property(readonly, nonatomic) SCSponsoredSlug *sponsoredSlug; // @synthesize sponsoredSlug=_sponsoredSlug;
@property(readonly, nonatomic) _Bool isFrameFilter; // @synthesize isFrameFilter=_isFrameFilter;
@property(readonly, nonatomic) _Bool isSponsored; // @synthesize isSponsored=_isSponsored;
@property(readonly, nonatomic) unsigned long long targetingType; // @synthesize targetingType=_targetingType;
@property(nonatomic) unsigned long long positionSetting; // @synthesize positionSetting=_positionSetting;
@property(nonatomic) long long scaleSetting; // @synthesize scaleSetting=_scaleSetting;
@property(readonly, nonatomic) long long priority; // @synthesize priority=_priority;
@property(readonly, nonatomic) long long unlockableContentType; // @synthesize unlockableContentType=_unlockableContentType;
@property(copy, nonatomic) NSString *filterId; // @synthesize filterId=_filterId;
@property(readonly, nonatomic) long long eligibility; // @synthesize eligibility=_eligibility;
@property(readonly, nonatomic) double assetTTL; // @synthesize assetTTL=_assetTTL;
@property(retain, nonatomic) NSDate *expirationDate; // @synthesize expirationDate=_expirationDate;
//- (void).cxx_destruct;
@property(readonly, nonatomic) _Bool isBitmoji;
@property(readonly, nonatomic) _Bool isFriendFilter;
@property(readonly, nonatomic) _Bool isActionmoji;
- (id)urlAttachment;
- (long long)geofilterMissLoggingType;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)imageLoadingKey:(id)arg1;
- (id)geofilterIdFenceIdCombinationKey;
//- (void)prepareGeoFilterImageWithCompletion:(CDUnknownBlockType)arg1 imageURLParamsMutator:(id)arg2 contextData:(id)arg3;
//- (void)geoFilterImageWithCompletion:(CDUnknownBlockType)arg1 imageURLParamsMutator:(id)arg2 contextData:(id)arg3;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)mapUnlockablesContext:(id)arg1;
- (id)initWithDictionary:(id)arg1 isPreCached:(_Bool)arg2;
- (id)initWithDictionary:(id)arg1;
- (id)initWithLocationId:(id)arg1 geoFenceLocationPoints:(id)arg2 filterId:(id)arg3 expirationDate:(id)arg4 scaleSetting:(long long)arg5 positionSetting:(unsigned long long)arg6 isSponsored:(_Bool)arg7 sponsoredSlug:(id)arg8 targetingType:(unsigned long long)arg9 autoRefreshDelayInMilliseconds:(long long)arg10 autoRefreshLabelPosition:(struct CGPoint)arg11 dynamicFilterRefreshHint:(id)arg12 dynamicFilterUpdatingMessage:(id)arg13 belowDrawingLayer:(_Bool)arg14 isAnimated:(_Bool)arg15 encryptedGeoData:(id)arg16 unlockableContentType:(long long)arg17 isFrameFilter:(_Bool)arg18 unlockableTrackInfo:(id)arg19 imageURL:(id)arg20 imageURLParams:(id)arg21 dynamicContextProperties:(id)arg22 autoStacking:(long long)arg23;
- (id)initWithFilterId:(id)arg1;
- (_Bool)filterPassesInclusionChecksWithLocationCircle:(id)arg1;

@end

