//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIKit.h>

//#import "UIGestureRecognizerDelegate-Protocol.h"

//@class NSString, UIImage, UIImageView, UILongPressGestureRecognizer;
//@protocol SCGrowingButtonDebugDelegate;

@interface SCGrowingButton : UIView <UIGestureRecognizerDelegate>
//{
//    _Bool _recognizesGesturesSimultaneously;
//    _Bool _useConstraintsForImage;
//    _Bool _onlyScaleImage;
//    _Bool _pressed;
//    _Bool _enabled;
//    UIImage *_image;
//    UIImageView *_imageView;
//    double _maximumScale;
//    double _minimumScale;
//    UIView *_extraAnimationView;
//    NSString *_imageName;
//    id <SCGrowingButtonDebugDelegate> _debugDelegate;
//    SEL _action;
//    UILongPressGestureRecognizer *_longPressGesture;
//    id _target;
//    struct CGSize _imageInset;
//    struct UIEdgeInsets _touchTargetInsets;
//}

@property(nonatomic) __weak id target; // @synthesize target=_target;
@property(retain, nonatomic) UILongPressGestureRecognizer *longPressGesture; // @synthesize longPressGesture=_longPressGesture;
@property(nonatomic) SEL action; // @synthesize action=_action;
//@property(nonatomic) __weak id <SCGrowingButtonDebugDelegate> debugDelegate; // @synthesize debugDelegate=_debugDelegate;
@property(nonatomic) struct UIEdgeInsets touchTargetInsets; // @synthesize touchTargetInsets=_touchTargetInsets;
@property(retain, nonatomic) NSString *imageName; // @synthesize imageName=_imageName;
@property(nonatomic, getter=isEnabled) _Bool enabled; // @synthesize enabled=_enabled;
@property(retain, nonatomic) UIView *extraAnimationView; // @synthesize extraAnimationView=_extraAnimationView;
@property(nonatomic, getter=isPressed) _Bool pressed; // @synthesize pressed=_pressed;
@property(nonatomic) _Bool onlyScaleImage; // @synthesize onlyScaleImage=_onlyScaleImage;
@property(nonatomic) _Bool useConstraintsForImage; // @synthesize useConstraintsForImage=_useConstraintsForImage;
@property(nonatomic) _Bool recognizesGesturesSimultaneously; // @synthesize recognizesGesturesSimultaneously=_recognizesGesturesSimultaneously;
@property(nonatomic) double minimumScale; // @synthesize minimumScale=_minimumScale;
@property(nonatomic) double maximumScale; // @synthesize maximumScale=_maximumScale;
@property(nonatomic) struct CGSize imageInset; // @synthesize imageInset=_imageInset;
@property(readonly, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
//- (void).cxx_destruct;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (_Bool)isAccessibilityElement;
- (void)interruptGestures;
- (void)cancelExistingTransformAnimationsIfNeeded;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)addTarget:(id)arg1 action:(SEL)arg2;
- (void)animate;
- (void)shrink;
- (void)grow;
//- (void)animateButtonSizeScale:(double)arg1 alpha:(double)arg2 completion:(CDUnknownBlockType)arg3;
- (void)press:(id)arg1;
- (void)layoutSubviews;
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
//@property(readonly, copy) NSString *debugDescription;
//@property(readonly, copy) NSString *description;
//@property(readonly) unsigned long long hash;
//@property(readonly) Class superclass;

@end

