//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2017 17:44:06).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIKit.h>

//#import "GenericSettingsViewController.h"
//
//#import "MyProfileStoryCellDelegate-Protocol.h"
//#import "SCExportMyStoriesManagerDelegate-Protocol.h"
//#import "SCGroupStoryGeoPrivacySettingsViewController_Old-Protocol.h"
//#import "SCGroupStoryGeofenceCellDelegate-Protocol.h"
//#import "SCGroupStoryMapCellDelegate-Protocol.h"
//#import "SCGroupStorySelectMembersViewController_DEPRECATED_Delegate-Protocol.h"
//#import "SCLocationServicesListener-Protocol.h"
//#import "SCMiniProfileViewControllerDelegate-Protocol.h"
//#import "SCMyStoriesCellDelegate-Protocol.h"
//#import "SCStoriesModelUpdateListener-Protocol.h"
//#import "SCStoryMediaStateListener-Protocol.h"
//#import "SCStoryPresenterDelegate-Protocol.h"
//#import "UIGestureRecognizerDelegate-Protocol.h"
//#import "UITableViewDataSource-Protocol.h"
//#import "UITableViewDelegate-Protocol.h"
//#import "UITextFieldDelegate-Protocol.h"

//@class CLLocation, NSArray, NSDictionary, NSNumber, NSString, SCAlertViewActionButtonController, SCExportMyStoriesManager, SCGroupStoryCreationSession, SCGroupStoryCreationSettings, SCHeaderAccessoryView, SCLoadingIndicatorView, SCMyGroupStories, SCStoryPresenter_DEPRECATED, SCUserSession, UIButton, UIColor, UIImage, UILabel, UIPanGestureRecognizer, UITableView, UITapGestureRecognizer, UIView, UIViewController;
//@protocol SCGroupStoryPrepostViewControllerDelegate, SCReplyDelegate;

@interface SCGroupStoryPrepostViewController : UIViewController
//<SCExportMyStoriesManagerDelegate, SCGroupStoryGeofenceCellDelegate, SCGroupStoryGeoPrivacySettingsViewController_Old, SCGroupStorySelectMembersViewController_DEPRECATED_Delegate, SCLocationServicesListener, SCMyStoriesCellDelegate, MyProfileStoryCellDelegate, SCStoryPresenterDelegate, UIGestureRecognizerDelegate, UITableViewDelegate, SCStoryMediaStateListener, UITableViewDataSource, UITextFieldDelegate, SCGroupStoryMapCellDelegate, SCMiniProfileViewControllerDelegate, SCStoriesModelUpdateListener>
//{
//    UITableView *_tableView;
//    UIView *_greyOverlay;
//    UILabel *_footerSubtextLabel;
//    UIViewController *_parentViewController;
//    SCGroupStoryCreationSettings *_postingSettings;
//    NSString *_publicationId;
//    NSNumber *_creationTimestamp;
//    NSString *_creatorId;
//    NSString *_creatorUsername;
//    NSString *_creatorDisplayName;
//    NSDictionary *_usernameDict;
//    NSDictionary *_displayNameDict;
//    NSArray *_originalPosterIds;
//    NSArray *_originalViewerIds;
//    NSArray *_sections;
//    UIButton *_createStoryButton;
//    SCLoadingIndicatorView *_createButtonSpinner;
//    CLLocation *_location;
//    NSString *_reverseGeocodeDetail;
//    UIColor *_tintColor;
//    unsigned long long _actionButtonStyle;
//    unsigned long long _optionsArrayButtonStyle;
//    unsigned long long _optionsArrayCancelButtonStyle;
//    UIImage *_backButtonImage;
//    UIImage *_backButtonPressedImage;
//    SCMyGroupStories *_myGroupStories;
//    SCUserSession *_userSession;
//    SCExportMyStoriesManager *_exportMyStoriesManager;
//    SCStoryPresenter_DEPRECATED *_storyPresenter;
//    id <SCReplyDelegate> _replyDelegate;
//    UITapGestureRecognizer *_tapGestureRecognizer;
//    UIView *_loadingView;
//    _Bool _viewHasLoaded;
//    _Bool _findingLocation;
//    _Bool _modifiedSettings;
//    _Bool _fetchingMetadata;
//    _Bool _isExpanded;
//    _Bool _editing;
//    _Bool _hideStories;
//    _Bool _inactive;
//    _Bool _isGroupChatPublication;
//    _Bool _isSaving;
//    SCGroupStoryCreationSession *_creationSession;
//    long long _sourceType;
//    long long _storyType;
//    UIPanGestureRecognizer *_panCancelGesture;
//    UIPanGestureRecognizer *_verticalDismissGesture;
//    SCHeaderAccessoryView *_groupStoryEditPencilIconView;
//    SCAlertViewActionButtonController *_namingSaveAction;
//    id <SCGroupStoryPrepostViewControllerDelegate> _delegate;
//    long long _context;
//}
//
//@property(nonatomic) long long context; // @synthesize context=_context;
//@property(nonatomic) __weak id <SCGroupStoryPrepostViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
//- (void).cxx_destruct;
//- (void)_logCreationSession;
//- (void)_updateCreationSession;
//- (void)mapCellDidFinishLoading;
//- (void)textFieldDidChange:(id)arg1;
//- (_Bool)textFieldShouldReturn:(id)arg1;
//- (void)textFieldDidBeginEditing:(id)arg1;
//- (void)miniProfileController:(id)arg1 wantsToNavigateToChatWithDeepLinkURL:(id)arg2;
//- (void)story:(id)arg1 didChangeThumbnailMediaState:(long long)arg2;
//- (void)story:(id)arg1 didChangeMediaState:(long long)arg2;
//- (void)storiesModelDidUpdateWithParams:(id)arg1;
//- (void)geoPrivacySettingsViewController:(id)arg1 didUpdatePrivacyType:(long long)arg2;
//- (void)_didUpdateGroupStories:(id)arg1;
//- (void)storyPresenter:(id)arg1 didFinishViewingFriendStories:(id)arg2 firstStoryDisplayed:(id)arg3 isReplayMode:(_Bool)arg4 becameFullyViewed:(_Bool)arg5;
//- (void)storyPresenter:(id)arg1 didBeginPlayingFriendStories:(id)arg2;
//- (void)storyPresenterWillBeginPlayingStory:(id)arg1 friendStories:(id)arg2 viewLocation:(long long)arg3;
//- (void)storyPresenterDidFinishDismissingStory:(id)arg1;
//- (void)storyPresenterDidCancelDismissingStory:(id)arg1;
//- (void)storyPresenterWillBeginAnimatingToDismissStory:(id)arg1;
//- (void)storyPresenterDidFinishPresentingStory:(id)arg1;
//- (void)storyPresenterWillBeginPresentingStory:(id)arg1;
//- (void)storyPresenter:(id)arg1 beginDismissFriendStories:(id)arg2 previousFriendStories:(id)arg3;
//- (void)storyPresenter:(id)arg1 didDismissFriendStories:(id)arg2 becameFullyViewed:(_Bool)arg3 succeededToPresent:(_Bool)arg4 viewingType:(long long)arg5;
//- (void)updateSaveMyStories:(id)arg1 withProgress:(double)arg2;
//- (void)handleSavedMyStories:(id)arg1 withError:(id)arg2;
//- (void)handleStartSavingMyStories;
//- (void)viewersPressedInCell:(id)arg1 forMyStory:(id)arg2;
//- (void)deletePressedForStory:(id)arg1;
//- (void)savePressedForStory:(id)arg1;
//- (void)showPhotoAccessDeniedAlertView;
//- (void)savePressedForMyStories:(id)arg1;
//- (void)myContributionStoryInfoPressedForMyStories:(id)arg1;
//- (void)addToMyStoryPressedForMyStories:(id)arg1;
//- (void)myStorySettingButtonPressedForMyStories:(id)arg1;
//- (void)_expandMyStories;
//- (void)expandMyStoryButtonPressedForMyStories:(id)arg1;
//- (void)_removeInvalidFriendsFromPermissions;
//- (void)groupStorySelectMembersViewController:(id)arg1 updateCustomGroupStoryPrivacyWithPosterIds:(id)arg2 viewerIds:(id)arg3 modifiedSettings:(_Bool)arg4 storyType:(long long)arg5;
//- (double)_heightToOffsetFooter;
//- (double)_heightOfTableViewCells;
//- (id)_currentMyStoriesCell;
//- (void)_setupTextForUserSelectionCell:(id)arg1 inSection:(unsigned long long)arg2;
//- (id)_sectionsTemplate;
//- (void)_updateWhoCanPostWithTextAnimated:(_Bool)arg1;
//- (void)_enableCreateButtonIfPossible;
//- (void)_setWhoCanViewPostUserInteractionEnabled:(_Bool)arg1;
//- (void)_updateCell:(id)arg1 enabled:(_Bool)arg2;
//- (void)_setCreateButtonEnabled:(_Bool)arg1;
//- (void)_setAutosaveToggleEnabled:(_Bool)arg1;
//- (void)_setAllButtonsEnabled:(_Bool)arg1;
//- (void)_addUserIdToViewers:(id)arg1;
//- (void)_addUserIdToPosters:(id)arg1;
//- (void)_removeUserIdFromViewers:(id)arg1;
//- (void)_removeUserIdFromPosters:(id)arg1;
//- (id)_groupStoryOptionsArrayForGroupChatParticipant;
//- (id)_groupStoryOptionsArrayForParticipant;
//- (id)_groupStoryOptionsArrayForCreator;
//- (void)_leaveGroupChatStory;
//- (void)_leaveGroupStoryByBlocking:(_Bool)arg1;
//- (void)_blockGroupStory;
//- (void)_leaveGroupStory;
//- (void)_deleteGroupStory;
//- (void)_alertToConfirmDiscardChanges;
//- (_Bool)_isDirty;
//- (id)_successfulCreateInAppNotification;
//- (id)_chooseDisplayNamePlaceholderTextForType:(long long)arg1;
//- (void)_showEnterDisplayNameAlert;
//- (void)_showOopsAlertWithTitle:(id)arg1 description:(id)arg2 showKeepEditing:(_Bool)arg3;
//- (void)_showOopsAlertForResponseCode:(long long)arg1 showKeepEditing:(_Bool)arg2;
//- (void)_createGroupStoryWithCurrentPostingSettings;
//- (void)_createStoryButtonPressed;
//- (id)textColorForHeader:(id)arg1;
//- (id)textColorForPlaceholderInHeader:(id)arg1;
//- (id)placeHolderForHeaderTextField;
//- (_Bool)shouldEnableTextField:(id)arg1;
//- (void)_updateSettingsToCurrentConfigs;
//- (void)leftButtonPressed;
//- (void)_dismissInContextAnimated:(_Bool)arg1;
//- (_Bool)_isBottomController;
//- (void)_updateDisplayName;
//- (void)rightButtonPressed;
//- (id)_trimmedHeaderTextField;
//- (long long)maxLengthForHeaderTextField:(id)arg1;
//- (void)headerTextFieldTextEditingChanged;
//- (void)headerTextFieldTextEditingDidBegin;
//- (void)headerTextFieldTextEditingDidEnd;
//- (id)viewForTitleInHeader:(id)arg1;
//- (id)imageForRightButtonInState:(unsigned long long)arg1;
//- (id)imageForLeftButtonInState:(unsigned long long)arg1;
//- (void)didUpdateLocation:(id)arg1;
//- (void)_updatePrivacyFooterSubtext;
//- (void)_updateFooterSubtextView;
//- (id)_fireStringForDaysActive:(long long)arg1;
//- (long long)_daysSinceCreation:(id)arg1 timeNow:(id)arg2;
//- (id)_subtextLessThanOneDay:(id)arg1 timeNow:(id)arg2;
//- (id)_timeAgoCreatedWithFires;
//- (id)_footerSubtext;
- (void)_updateLocation;
//- (void)_fillInGeofenceDetails;
//- (CDUnknownBlockType)_locationPermissionsActionHandler;
//- (void)_authorizeAndUpdateLocation;
//- (void)_resetGeofenceToOff;
//- (void)_updateWhoCanPostWhoCanView;
//- (id)_currentWhoCanViewCell;
//- (id)_currentWhoCanPostCell;
//- (id)_currentAutosaveCell;
//- (id)_currentGeofenceCell;
//- (id)_currentMapCell;
//- (void)_updateGeofenceAddress;
//- (void)geofenceCellDidPressEdit:(id)arg1;
//- (void)geofenceCellSwitchDidChange:(id)arg1;
//- (_Bool)_allowsAddToStory;
//- (id)_whoCanViewCell;
//- (id)_whoCanPostCell;
//- (id)_userSelectorCellForidentifier:(id)arg1;
//- (void)_autosaveToggleChanged:(id)arg1;
//- (id)_autosaveCell;
//- (id)_geofenceCell;
//- (id)_mapCell;
//- (id)_myStoryCellAtIndexPath:(id)arg1;
//- (id)_myGroupStoriesCell;
//- (void)_presentStoryUsingOperaWithFriendStories:(id)arg1 story:(id)arg2 viewLocationPosition:(unsigned long long)arg3 showViewersTable:(_Bool)arg4 baseView:(id)arg5;
//- (void)_didSelectCell:(id)arg1 withStory:(id)arg2;
//- (void)_addToMyStories:(id)arg1;
//- (void)_didSelectStoriesCell:(id)arg1;
//- (void)_showCustomViewerPosterInfoWithTitle:(id)arg1 isWhoCanPostCell:(_Bool)arg2;
//- (void)_showGeofenceViewerPosterInfo:(_Bool)arg1;
//- (void)_didSelectViewPostCell:(_Bool)arg1;
//- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
//- (void)_dismissKeyboard;
//- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
//- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
//- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
//- (void)_updateStoriesHeaderCell;
//- (void)_updateCellWithStory:(id)arg1;
//- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
//- (unsigned long long)_sectionForIndexPath:(id)arg1;
//- (unsigned long long)_sectionForIndexSection:(long long)arg1;
//- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
//- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
//- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
//- (long long)numberOfSectionsInTableView:(id)arg1;
//- (_Bool)_canOnlyCreateFriendsGeoStory;
//- (_Bool)_isCreator;
//- (void)didFinishUpdatingPublicationMetadata:(id)arg1;
//- (_Bool)_missingGroupStoriesMetadata;
//- (void)_fetchMetadataForGroupStories:(id)arg1;
//- (id)_groupStoryCollection;
//- (void)dealloc;
//- (void)_setupLoadingView;
//- (void)_setupPrivacyFooterSubtext;
//- (void)_presentMiniProfileOfCreator;
//- (void)_setupStreaksFooterSubtext;
//- (void)_setupFooterSubtext;
//- (void)_setupCreateStoryButton;
//- (void)_setupGreyOverlay;
//- (void)_setupTableView;
//- (_Bool)shouldPopToRootViewController;
//- (void)handlePopRecognizer:(id)arg1;
//- (void)_handleVerticalDismissGesture:(id)arg1;
//- (void)_handlePanToCancelCreate:(id)arg1;
//- (void)viewDidAppear:(_Bool)arg1;
//- (void)viewWillAppear:(_Bool)arg1;
//- (void)viewDidLoad;
//- (id)initWithGroupStoryPublicationToEdit:(id)arg1 showExpanded:(_Bool)arg2 hideStories:(_Bool)arg3 userSession:(id)arg4 replyDelegate:(id)arg5 sourceType:(long long)arg6 fromContext:(long long)arg7;
//- (id)initWithCreationContext:(long long)arg1 userSession:(id)arg2 creationSettings:(id)arg3 fromViewController:(id)arg4 storyType:(long long)arg5 creationSession:(id)arg6;
//
//// Remaining properties
//@property(readonly, copy) NSString *debugDescription;
//@property(readonly, copy) NSString *description;
//@property(readonly) unsigned long long hash;
//@property(readonly) Class superclass;

@end

