//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2017 17:44:06).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@protocol SCHeaderDelegate <NSObject>

@optional
- (void)xButtonPressed;
- (void)headerTextFieldTextDidEditingDidEndOnExit;
- (void)headerTextFieldTextEditingDidBegin;
- (void)headerTextFieldTextEditingDidEnd;
- (void)headerTextFieldTextEditingChanged;
- (void)fadeHeaderForNotification:(_Bool)arg1;
- (double)preferredRightButtonWidth;
- (double)preferredLeftButtonWidth;
- (void)rightButtonPressed;
- (void)leftButtonPressed;
@end

