//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2017 17:44:06).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIKit.h>
//#import "SCHeaderDelegate-Protocol.h"
//#import "SCHeaderDataSource-Protocol.h"

//#import "SCTimeProfilable-Protocol.h"
//#import "UITextFieldDelegate-Protocol.h"

//@class CAShapeLayer, NSString, SCBottomBorderedView, SCHeaderAccessoryView, SCSearchBar, SCShapeView, UIButton, UIColor, UILabel, UITextField;
@protocol SCHeaderDataSource, SCHeaderDelegate;

@interface SCHeader : UIView
//<UITextFieldDelegate>
//{
////    SCShapeView *_cardView;
//    unsigned long long _cardViewStyle;
//    struct CGSize _attributedPlaceholderSize;
//    _Bool _centerLabelNoButtonOffset;
////    id <SCHeaderDataSource> _dataSource;
////    id <SCHeaderDelegate> _delegate;
//    UIButton *_leftButton;
//    UIButton *_rightButton;
//    UIColor *_borderColor;
//    double _borderThickness;
////    SCHeaderAccessoryView *_accessoryHeaderView;
//    UIView *_leftOverlayView;
//    UIView *_rightOverlayView;
//    UILabel *_headerLabel;
//    UITextField *_headerTextField;
//    SCSearchBar *_headerSearchBar;
//    double _topInset;
//    double _height;
//    unsigned long long _corners;
////    SCBottomBorderedView *_bottomBorderedView;
//    unsigned long long _style;
//    UIButton *_xButton;
//    UIView *_headerViewToUpdate;
//}
//
//+ (int)context;
////+ (Class)layerClass;
//@property(retain, nonatomic) UIView *headerViewToUpdate; // @synthesize headerViewToUpdate=_headerViewToUpdate;
//@property(retain, nonatomic) UIButton *xButton; // @synthesize xButton=_xButton;
//@property(nonatomic) unsigned long long style; // @synthesize style=_style;
////@property(retain, nonatomic) SCBottomBorderedView *bottomBorderedView; // @synthesize bottomBorderedView=_bottomBorderedView;
//@property(nonatomic) unsigned long long corners; // @synthesize corners=_corners;
//@property(readonly, nonatomic) double height; // @synthesize height=_height;
//@property(readonly, nonatomic) double topInset; // @synthesize topInset=_topInset;
//@property(nonatomic) _Bool centerLabelNoButtonOffset; // @synthesize centerLabelNoButtonOffset=_centerLabelNoButtonOffset;
//@property(readonly, nonatomic) SCSearchBar *headerSearchBar; // @synthesize headerSearchBar=_headerSearchBar;
//@property(readonly, nonatomic) UITextField *headerTextField; // @synthesize headerTextField=_headerTextField;
//@property(retain, nonatomic) UILabel *headerLabel; // @synthesize headerLabel=_headerLabel;
//@property(retain, nonatomic) UIView *rightOverlayView; // @synthesize rightOverlayView=_rightOverlayView;
//@property(retain, nonatomic) UIView *leftOverlayView; // @synthesize leftOverlayView=_leftOverlayView;
////@property(retain, nonatomic) SCHeaderAccessoryView *accessoryHeaderView; // @synthesize accessoryHeaderView=_accessoryHeaderView;
//@property(nonatomic) double borderThickness; // @synthesize borderThickness=_borderThickness;
//@property(retain, nonatomic) UIColor *borderColor; // @synthesize borderColor=_borderColor;
@property(retain, nonatomic) UIButton *rightButton; // @synthesize rightButton=_rightButton;
@property(retain, nonatomic) UIButton *leftButton; // @synthesize leftButton=_leftButton;
//@property(nonatomic) __weak id <SCHeaderDelegate> delegate; // @synthesize delegate=_delegate;
//@property(nonatomic) __weak id <SCHeaderDataSource> dataSource; // @synthesize dataSource=_dataSource;
////- (void).cxx_destruct;
//- (double)additionalXOffsetForHeader;
//- (double)rightButtonWidth;
//- (double)leftButtonWidth;
//- (void)rightButtonPressed;
//- (void)leftButtonPressed;
//- (_Bool)shouldAddCardView;
//- (void)_showXButtonIfNecessary;
//- (id)font;
//- (struct CGSize)cachedAttributedPlaceholderSize;
//- (struct CGSize)textSize;
//@property(retain, nonatomic) NSString *text;
//- (void)xButtonPressed;
//- (void)_textFieldEditingDidEndOnExit;
//- (void)_textFieldEditingDidBegin;
//- (void)_textFieldEditingDidEnd;
//- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
//- (void)_textFieldEditingChanged;
//- (void)fadeImageInHeader:(_Bool)arg1;
//- (void)setupTapGestureForRightOverlay;
//- (void)_updateAccessoryViewInHeaderIfNecessary;
//- (void)_adjustFontIfNecessary;
//- (void)_updateButtons;
//- (void)_updateHeaderSearchBar;
//- (void)_updateHeaderTextField;
//- (void)_updateHeaderLabel;
//- (void)_updateHeaderView;
//- (void)reloadData;
//@property(readonly, nonatomic) CAShapeLayer *shapeLayer;
//- (struct CGSize)intrinsicContentSize;
//- (void)setupRightButton;
//- (void)setupLeftButton;
//- (void)_setupCardView;
//- (void)_setupSearchBar;
//- (void)_setupTextField;
//- (void)_setupHeaderLabel;
//- (void)setupBottomBorder;
//- (double)_headerContentViewWidth;
//- (unsigned long long)_positionWithRTL;
//- (void)_layoutHeaderView;
//- (void)layoutSubviews;
//- (id)initWithoutInset;
//- (id)initWithoutBottomBorder;
//- (id)initWithBottomBorderAndWhiteCardViewForXWithStyle:(unsigned long long)arg1;
//- (id)initWithBottomBorderAndWhiteCardViewForX;
//- (id)initWithBottomBorder;
//- (id)initWithStyle:(unsigned long long)arg1 withBottomBorder:(_Bool)arg2 cardViewStyle:(unsigned long long)arg3;
//- (id)initWithStyle:(unsigned long long)arg1 withBottomBorder:(_Bool)arg2;
//- (id)initWithFrame:(struct CGRect)arg1 style:(unsigned long long)arg2 withBottomBorder:(_Bool)arg3 inset:(double)arg4 cardViewStyle:(unsigned long long)arg5;
//- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
//@property(readonly, copy) NSString *debugDescription;
//@property(readonly, copy) NSString *description;
//@property(readonly) unsigned long long hash;
//@property(readonly) Class superclass;

@end

