//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/Foundation.h>

//#import "NSCopying-Protocol.h"

//@class NSArray, NSData, NSString, NSValue;

@interface SCM3U8 : NSObject <NSCopying>
{
    NSString *_string;
}

@property(readonly, nonatomic) NSString *string; // @synthesize string=_string;
//- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)M3U8ByUpdatingURLSWithURLS:(id)arg1;
- (id)_mediaURLByteRanges;
- (id)_mediaURLS;
@property(readonly, nonatomic) NSValue *videoSize;
@property(readonly, nonatomic) NSArray *mediaSegmentInfos;
@property(readonly, nonatomic) NSArray *childM3U8Urls;
@property(readonly, nonatomic) NSArray *urls;
@property(readonly, nonatomic) NSData *data;
- (id)initWithString:(id)arg1;
- (id)initWithData:(id)arg1;

@end

