//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2017 17:44:06).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//


#import "UIView-SnapAppDel.h"

@interface SCMediaView : UIView

@property(retain, nonatomic) UIImageView *imageView;
- (void)hideMedia;
@end
