//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIKit.h>

//#import "SCOperaLayerView-Protocol.h"

//@class NSString, SCAffordanceArrowView, SCGradientView, UIButton, UIColor, UIFont, UIImageView, UILabel;

@interface SCOperaArrowLayerView : UIView
//<SCOperaLayerView>
//{
//    SCAffordanceArrowView *_arrowView;
//    UILabel *_textLabel;
//    UIImageView *_gradientView;
//    SCGradientView *_bottomGradientView;
//    UIView *_fullWidthButtonView;
//    UILabel *_fullWidthButtonTextLabel;
//    UILabel *_fullWidthButtonSecondaryTextLabel;
//    UIView *_contextCardView;
//    UILabel *_contextCardViewTextLabel;
//    UIButton *_contextCardViewButton;
//    UIImageView *_contextCardImageView;
//    UIButton *_transparentButton;
//    unsigned long long _attachmentTriggerType;
//    _Bool _textTitleCaseEnabled;
//    double _textKerningSize;
//    double _offsetBetweenLabelAndArrow;
//    double _arrowTopOffset;
//    double _fullWidthButtonViewHeight;
//    long long _fullWidthButtonTextFontSize;
//    double _fullWidthButtonTextKerningSize;
//    UIColor *_fullWidthButtonSecondaryTextColor;
//    UIFont *_fullWidthButtonSecondaryTextFont;
//    double _fullWidthButtonSecondaryTextRightOffset;
//    double _fullWidthButtonViewTopOffset;
//    double _contextCardViewTopOffset;
//    double _contextCardTextKerningSize;
//    unsigned long long _contextCardTextFontSize;
//    double _contextCardTextLabelTopOffset;
//    double _contextCardImageViewLeftOffset;
//    double _contextCardImageViewTopOffset;
//    double _contextCardImageViewHeight;
//    double _contextCardOffsetBetweenImageViewAndTextLabel;
//    double _contextCardButtonCornerRadius;
//    double _contextCardButtonBorderWidth;
//    unsigned long long _contextCardButtonTitleFont;
//    double _contextCardButtonTopAndBottomEdgeInset;
//    double _contextCardButtonLeftAndRightEdgeInset;
//    double _contextCardButtonRightOffset;
//    double _contextCardTopOffset;
//    double _contextCardLeftAndRightOffset;
//    double _contextCardHeight;
//    double _transparentButtonTopOffset;
//    _Bool _hasGradient;
//    _Bool _hasBottomGradient;
//    double _opacity;
//    NSString *_text;
//    double _arrowViewTopOffset;
//    long long _textFontSize;
//}
//
//+ (id)layerViewWithFrame:(struct CGRect)arg1;
//@property(nonatomic) _Bool hasBottomGradient; // @synthesize hasBottomGradient=_hasBottomGradient;
//@property(nonatomic) long long textFontSize; // @synthesize textFontSize=_textFontSize;
//@property(nonatomic) double arrowViewTopOffset; // @synthesize arrowViewTopOffset=_arrowViewTopOffset;
//@property(copy, nonatomic) NSString *text; // @synthesize text=_text;
//@property(nonatomic) double opacity; // @synthesize opacity=_opacity;
//@property(nonatomic) _Bool hasGradient; // @synthesize hasGradient=_hasGradient;
//- (void).cxx_destruct;
//- (struct CGRect)transparentButtonBounds;
//- (void)_setTransparentButton:(id)arg1;
//- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
//- (void)_showCurrentAttachmentTriggerView;
//- (void)hideAttachmentTriggerView;
//- (void)showAttachmentTriggerViewAnimated;
//- (struct CGRect)contextCardViewBounds;
//- (void)_setContextCardButton:(id)arg1;
//- (void)_setContextCardImage:(id)arg1;
//- (void)_setContextCardText:(id)arg1;
//- (void)_setupContextCardView:(id)arg1 contextCardIcon:(id)arg2 contextCardButtonTitleText:(id)arg3 contextCardHasBottomGradient:(_Bool)arg4;
//- (void)_setupFullWidthButtonView;
//- (struct CGRect)_bottomGradientViewFrame;
//- (void)layoutSubviews;
//- (void)updateVisible:(_Bool)arg1 animationDuration:(double)arg2 delay:(double)arg3;
//- (void)_setFullWidthButtonSecondaryText:(id)arg1;
//- (void)_setFullWidthButtonText:(id)arg1;
//- (void)_setText:(id)arg1;
//- (void)_setupArrowView;
//- (void)_setupTransparentButtonForLayer:(id)arg1;
//- (void)_setupContextCardViewForLayer:(id)arg1;
//- (void)_setupFullWidthButtonViewForLayer:(id)arg1;
//- (void)_setupTextLabelForLayer:(id)arg1;
//- (void)setupViewForLayer:(id)arg1;
//- (id)initWithFrame:(struct CGRect)arg1;
//
//// Remaining properties
//@property(readonly, copy) NSString *debugDescription;
//@property(readonly, copy) NSString *description;
//@property(readonly) unsigned long long hash;
//@property(readonly) Class superclass;

@end

