//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIKit.h>
#import "UIView-SnapAppDel.h"

//#import "SCPreviewDeletionGestureHandler-Protocol.h"
//#import "SCPreviewToolBarButtonItemDelegate-Protocol.h"
//#import "UIGestureRecognizerDelegate-Protocol.h"

//@class NSArray, NSMapTable, NSString, SCGradientView, SCPreviewToolBarButtonItem, SCPreviewToolbarLongPressGestureRecognizer, SCPreviewToolbarScrollView, UIImageView, UILabel;
//@protocol SCPreviewToolBarDelegate;

@interface SCPreviewToolBar : UIView
//<SCPreviewDeletionGestureHandler, SCPreviewToolBarButtonItemDelegate, UIGestureRecognizerDelegate>
//{
//    double _maxHeight;
//    _Bool _enabled;
//    _Bool _userHasTappedToolbarOrSendTo;
//    id <SCPreviewToolBarDelegate> _delegate;
//    NSArray *_items;
//    SCPreviewToolBarButtonItem *_selectedItem;
//    UIImageView *_lensAnimation;
//    UIImageView *_drawAnimation;
//    UILabel *_labelAnimation;
//    UIView *_labelCursorView;
//    UILabel *_stickerAnimation;
//    SCGradientView *_gradientMaskView;
//    SCPreviewToolBarButtonItem *_longPressingItem;
//    SCPreviewToolbarLongPressGestureRecognizer *_longPressGestureRecognizer;
//    NSMapTable *_tooltipViews;
//    SCPreviewToolbarScrollView *_scrollView;
//    long long _captionTooltipCharsTyped;
//}
//
//@property(nonatomic) long long captionTooltipCharsTyped; // @synthesize captionTooltipCharsTyped=_captionTooltipCharsTyped;
//@property(readonly, nonatomic) SCPreviewToolbarScrollView *scrollView; // @synthesize scrollView=_scrollView;
//@property(retain, nonatomic) NSMapTable *tooltipViews; // @synthesize tooltipViews=_tooltipViews;
//@property(retain, nonatomic) SCPreviewToolbarLongPressGestureRecognizer *longPressGestureRecognizer; // @synthesize longPressGestureRecognizer=_longPressGestureRecognizer;
//@property(retain, nonatomic) SCPreviewToolBarButtonItem *longPressingItem; // @synthesize longPressingItem=_longPressingItem;
//@property(retain, nonatomic) SCGradientView *gradientMaskView; // @synthesize gradientMaskView=_gradientMaskView;
//@property(nonatomic) _Bool userHasTappedToolbarOrSendTo; // @synthesize userHasTappedToolbarOrSendTo=_userHasTappedToolbarOrSendTo;
//@property(retain, nonatomic) UILabel *stickerAnimation; // @synthesize stickerAnimation=_stickerAnimation;
//@property(retain, nonatomic) UIView *labelCursorView; // @synthesize labelCursorView=_labelCursorView;
//@property(retain, nonatomic) UILabel *labelAnimation; // @synthesize labelAnimation=_labelAnimation;
//@property(retain, nonatomic) UIImageView *drawAnimation; // @synthesize drawAnimation=_drawAnimation;
//@property(retain, nonatomic) UIImageView *lensAnimation; // @synthesize lensAnimation=_lensAnimation;
//@property(nonatomic, getter=isEnabled) _Bool enabled; // @synthesize enabled=_enabled;
//@property(retain, nonatomic) SCPreviewToolBarButtonItem *selectedItem; // @synthesize selectedItem=_selectedItem;
//@property(copy, nonatomic) NSArray *items; // @synthesize items=_items;
//@property(nonatomic) __weak id <SCPreviewToolBarDelegate> delegate; // @synthesize delegate=_delegate;
//- (void).cxx_destruct;
//- (void)removeItemType:(long long)arg1;
//- (void)insertItem:(id)arg1 afterItemType:(long long)arg2 animated:(_Bool)arg3 completion:(CDUnknownBlockType)arg4;
//- (void)insertItem:(id)arg1 beforeItemType:(long long)arg2 animated:(_Bool)arg3 completion:(CDUnknownBlockType)arg4;
//- (void)_animateItemAppearance:(id)arg1 completion:(CDUnknownBlockType)arg2;
//- (struct CGRect)frameForButtonItemType:(long long)arg1 inView:(id)arg2;
//- (_Bool)isTooltipVisibleForItem:(id)arg1;
//- (void)dismissTooltipForItem:(id)arg1 animated:(_Bool)arg2;
//- (void)dismissAllTooltips:(_Bool)arg1;
//- (void)presentTooltipFromItem:(id)arg1 withTitle:(id)arg2;
//- (void)presentTooltipFromItem:(id)arg1 withTitle:(id)arg2 dismissalDelay:(double)arg3;
//- (id)tooltipViewForItem:(id)arg1;
//- (void)_animateBottomAccessoryViews;
//- (void)_adjustScrollViewContentHeight:(double)arg1;
//- (void)topAccessoryViewsAnimateToNewPositionWithoutView:(id)arg1;
//- (double)_layoutButtonAccessoryViews:(id)arg1 startY:(double)arg2 yDirection:(long long)arg3;
//- (void)_layoutBottomAccessoryViews:(id)arg1;
//- (void)_layoutTopAccessoryViews:(id)arg1;
//- (void)_layoutAccessoryViews;
//- (void)_layoutToolButtons;
//- (void)_updateToolButtonsVisibility;
//- (void)_hideAccessoryViewsForItem:(id)arg1;
//- (void)_addAccessoryViewsForItem:(id)arg1;
//- (void)_removeAccessoryViewsForItem:(id)arg1;
//- (void)_animateExitPreviouslySelectedItemMode:(id)arg1 completion:(CDUnknownBlockType)arg2;
//- (void)_animateEnterSelectedItemMode:(id)arg1;
//- (id)_itemForTouchLocation:(struct CGPoint)arg1;
//- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
//- (void)_longPress:(id)arg1;
//- (double)itemAccessoryViewsAnimationDuration;
//- (void)itemAccessoryViewsHaveChanged:(id)arg1 needAnimation:(_Bool)arg2;
//- (id)itemWithType:(long long)arg1;
//- (void)updateMaxHeight:(double)arg1;
//- (void)setSelectedItem:(id)arg1 animated:(_Bool)arg2;
//- (void)layoutSubviews;
//- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
//- (struct CGRect)_extendedGradientMaskViewFrame;
//- (id)initWithFrame:(struct CGRect)arg1;
//- (void)stopTooltipAnimations;
//- (void)_typeCaptionTooltipAnimation:(id)arg1;
//- (void)performTooltipAnimations:(long long)arg1;
//- (void)animateTooltipForToolbarItem:(id)arg1 animationView:(id)arg2 firstImage:(id)arg3 lastImage:(id)arg4 animationBlocks:(id)arg5 isInitialTransformAnimated:(_Bool)arg6 animationDuration:(double)arg7 getNextAnimation:(CDUnknownBlockType)arg8;
//- (id)_lensTooltipAnimation;
//- (id)_stickerTooltipAnimation;
//- (id)_labelTooltipAnimation;
//- (id)_drawingTooltipAnimation;
//- (void)setupTooltipAnimationViews;
//- (id)showTooltipWithText:(id)arg1 belowView:(id)arg2;
//- (_Bool)didEndDeletionGesture:(id)arg1 withView:(id)arg2 deleteAnimationCompletion:(CDUnknownBlockType)arg3;
//- (void)didMoveDeletionGesture:(id)arg1 withView:(id)arg2;
//- (_Bool)_trashContains:(id)arg1;
//- (void)didStartDeletionGesture;
//- (void)scrollToBottomIfNecessary;
//- (struct CGRect)trashcanFrameInView:(id)arg1;
//- (id)currentTrashcanItem;
//
//// Remaining properties
//@property(readonly, copy) NSString *debugDescription;
//@property(readonly, copy) NSString *description;
//@property(readonly) unsigned long long hash;
//@property(readonly) Class superclass;

@end

