//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/Foundation.h>

//@class PreviewTransitionController, PreviewViewController, SCPreviewConfiguration, SCRecordingMetadataProvider, SnapTrophyMetrics;
//@protocol SCLensProcessingCore;

@interface SCPreviewPresenter : NSObject
//{
//    SCPreviewConfiguration *_previewConfiguration;
//    PreviewViewController *_previewViewController;
//    SnapTrophyMetrics *_trophyMetrics;
//    PreviewTransitionController *_previewTransitionController;
//    SCRecordingMetadataProvider *_recordingMetadataProvider;
//    id <SCLensProcessingCore> _lensProcessingCore;
//}
//
//@property(readonly, nonatomic) id <SCLensProcessingCore> lensProcessingCore; // @synthesize lensProcessingCore=_lensProcessingCore;
//@property(retain, nonatomic) SCRecordingMetadataProvider *recordingMetadataProvider; // @synthesize recordingMetadataProvider=_recordingMetadataProvider;
//@property(retain, nonatomic) PreviewTransitionController *previewTransitionController; // @synthesize previewTransitionController=_previewTransitionController;
//@property(retain, nonatomic) SnapTrophyMetrics *trophyMetrics; // @synthesize trophyMetrics=_trophyMetrics;
//@property(retain, nonatomic) PreviewViewController *previewViewController; // @synthesize previewViewController=_previewViewController;
//@property(readonly, nonatomic) SCPreviewConfiguration *previewConfiguration; // @synthesize previewConfiguration=_previewConfiguration;
//- (void).cxx_destruct;
//- (id)_previewFilterDataProviderForMediaTypeContext:(long long)arg1;
//- (long long)_snapSource:(long long)arg1;
//- (unsigned long long)_suitableVideoPlaybackQuality;
//- (id)_unlockBackReferenceIdForAppliedLens:(id)arg1;
//- (id)_lensPreviewConfiguration:(id)arg1 managedCapturerState:(id)arg2 lensDataProvider:(id)arg3 lensSnapcodeARExperienceController:(id)arg4;
//- (void)_configureCommon:(id)arg1 managedCapturerState:(id)arg2 captionManager:(id)arg3 lensDataProvider:(id)arg4 lensSnapcodeARExperienceController:(id)arg5;
//- (void)setDeepLinkMetadata:(id)arg1;
//- (void)setStartRecordingTimestamp:(id)arg1;
//- (void)setPlaceholderImage:(id)arg1;
//- (void)setCaptureSessionID:(id)arg1;
//- (void)setSnapPageSource:(long long)arg1;
//- (void)setCameraFlipsWhileRecording:(long long)arg1;
//- (void)setMediaAspectRatio:(double)arg1;
//- (void)setMediaSize:(struct CGSize)arg1;
//- (void)setNightModeActive:(_Bool)arg1 nightModeHidden:(_Bool)arg2;
//- (void)setLowLightBoostEnabledBeforeCapture:(_Bool)arg1;
//- (void)setDidZoomWhileFilming:(_Bool)arg1;
//- (void)setHandsFree:(_Bool)arg1;
//- (void)setDidFilmSelf:(_Bool)arg1 flashActive:(_Bool)arg2;
//- (void)setAudioEnabled:(_Bool)arg1;
//- (void)setSnapSendPreparer:(id)arg1;
//- (void)setMultiSnapConfiguration:(id)arg1;
//- (void)setReplyParameters:(id)arg1 replyCameraType:(long long)arg2;
//- (_Bool)handsFree;
//- (_Bool)fromFrontFacingCamera;
//- (long long)cameraFlipsWhileRecording;
- (void)presentPreviewViewController:(id)arg1 async:(_Bool)arg2 completion:(id)arg3;
- (void)loadPreviewViewController;
- (void)createPreviewViewController:(id)arg1 startChatDelegate:(id)arg2 scanPreviewDelegate:(id)arg3;
//- (void)configureWithVideoFuture:(id)arg1 cameraOverlayView:(id)arg2 managedCapturerState:(id)arg3 captionManager:(id)arg4 lensDataProvider:(id)arg5 lensSnapcodeARExperienceController:(id)arg6;
//- (void)configureWithImageFuture:(id)arg1 cameraOverlayView:(id)arg2 managedCapturerState:(id)arg3 captionManager:(id)arg4 lensDataProvider:(id)arg5 lensSnapcodeARExperienceController:(id)arg6;
//- (id)initWithUserSession:(id)arg1 lensProcessingCore:(id)arg2 capturer:(id)arg3;

@end

