//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/Foundation.h>
#import "SCManagedRecordedVideo.h"

@class SCManagedRecordedVideo;

@interface SCRecordingFileManager : NSObject
//{
//    SCManagedRecordedVideo *_recordedVideo;
//}

@property(retain, nonatomic) SCManagedRecordedVideo *recordedVideo; // @synthesize recordedVideo=_recordedVideo;
//- (void).cxx_destruct;
- (void)removeActiveRecordingURLOfRecordedVideo;
- (_Bool)discardRecordedVideoIfNecessary;
- (void)removeActiveVideoURL:(id)arg1;
- (id)generateTempOutputURLAndAddActiveVideoURL;

@end

