//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/Foundation.h>
#import "Story.h"

//@class FriendStories, FriendStoriesCollection, NSMutableSet, NSString, SCOperaContextLongformViewLogger, SCOperaViewInteraction, SCRequestManager, SCStopwatch, SCStoriesViewingSession, SCStoryAdOrganizer, SCStoryDiagnosticsLogger, SCStoryLogger, SCStoryUsageLogger, SCUserSession, Story;
//@protocol SCStoriesAutoAdvanceAdsDelegate, SCStoriesOperaPageProvider, SCStoriesViewingHandler;

@interface SCSingleFriendStoriesViewingSession : NSObject
//{
//    SCStoryLogger *_storyLogger;
//    SCStoryUsageLogger *_usageLogger;
//    SCStoryDiagnosticsLogger *_diagnosticsLogger;
//    SCOperaContextLongformViewLogger *_operaLongformLogger;
//    id <SCStoriesOperaPageProvider> _operaPageProvider;
//    id <SCStoriesViewingHandler> _storiesViewingHandler;
//    id <SCStoriesAutoAdvanceAdsDelegate> _autoAdvanceAdsDelegate;
//    SCStoryAdOrganizer *_inStreamAdOrganizer;
//    SCUserSession *_userSession;
//    long long _viewingType;
//    SCRequestManager *_requestManager;
//    FriendStoriesCollection *_friendStoriesCollection;
//    double _totalTimeForUniqueViewedSnaps;
//    Story *_lastStoryStoppedPlaying;
//    SCStopwatch *_storyViewStopwatch;
//    SCStopwatch *_snapViewStopwatch;
//    SCStopwatch *_attachmentViewStopwatch;
//    _Bool _showingloadingScreen;
//    _Bool _friendStoriesHaveStartedPlaying;
//    NSMutableSet *_viewedStoriesClientIds;
//    _Bool _isInStoryPlaylistMode;
//    _Bool _didEnterFromInterstitial;
//    NSString *_mostRecentPlayableStoryClientIdOnEntry;
//    _Bool _didReachNewStoryNotInPartialResponse;
//    _Bool _didHitLoadingScreenForPartialResponse;
//    _Bool _didSwipeUp;
//    _Bool _currentStoryDidShowLoadingScreen;
//    _Bool _isFullyViewed;
//    _Bool _wasInitialyFullyViewed;
//    _Bool _currentStoryHasPlayed;
//    FriendStories *_friendStories;
//    Story *_firstStory;
//    Story *_currentStory;
//    unsigned long long _storyViewingActionContext;
//    unsigned long long _totalViewedSnapsCount;
//    unsigned long long _totalOpenedSnapsCount;
//    long long _mediaLoadContext;
//    long long _viewLocation;
//    SCStoriesViewingSession *_storiesViewingSession;
//    SCOperaViewInteraction *_entryInteraction;
//}
//
//@property(readonly, nonatomic) SCOperaViewInteraction *entryInteraction; // @synthesize entryInteraction=_entryInteraction;
//@property(readonly, nonatomic) __weak SCStoriesViewingSession *storiesViewingSession; // @synthesize storiesViewingSession=_storiesViewingSession;
//@property(readonly, nonatomic) long long viewLocation; // @synthesize viewLocation=_viewLocation;
//@property(readonly, nonatomic) long long mediaLoadContext; // @synthesize mediaLoadContext=_mediaLoadContext;
//@property(readonly, nonatomic) _Bool currentStoryHasPlayed; // @synthesize currentStoryHasPlayed=_currentStoryHasPlayed;
//@property(readonly, nonatomic) unsigned long long totalOpenedSnapsCount; // @synthesize totalOpenedSnapsCount=_totalOpenedSnapsCount;
//@property(readonly, nonatomic) unsigned long long totalViewedSnapsCount; // @synthesize totalViewedSnapsCount=_totalViewedSnapsCount;
//@property(readonly, nonatomic) _Bool wasInitialyFullyViewed; // @synthesize wasInitialyFullyViewed=_wasInitialyFullyViewed;
//@property(readonly, nonatomic) _Bool isFullyViewed; // @synthesize isFullyViewed=_isFullyViewed;
//@property(readonly, nonatomic) _Bool currentStoryDidShowLoadingScreen; // @synthesize currentStoryDidShowLoadingScreen=_currentStoryDidShowLoadingScreen;
//@property(readonly, nonatomic) unsigned long long storyViewingActionContext; // @synthesize storyViewingActionContext=_storyViewingActionContext;
//@property(readonly, nonatomic) _Bool didSwipeUp; // @synthesize didSwipeUp=_didSwipeUp;
@property(readonly, nonatomic) Story *currentStory; // @synthesize currentStory=_currentStory;
//@property(readonly, nonatomic) Story *firstStory; // @synthesize firstStory=_firstStory;
//@property(readonly, nonatomic) FriendStories *friendStories; // @synthesize friendStories=_friendStories;
//- (void).cxx_destruct;
//- (id)precedingStoriesDataModelForCurrentAdsStories;
//- (double)totalStoryTime;
//@property(readonly, nonatomic) unsigned long long totalSnapCount;
//- (double)viewedStoryTime;
//- (id)posterId;
//- (double)attachmentTimeViewedSec;
//- (double)snapTimeViewedSec;
//- (unsigned long long)uniqueViewedSnapsCount;
//- (_Bool)_disableAdSkipforContext:(id)arg1 params:(id)arg2;
//- (id)extraPropertiesForStory:(id)arg1;
//- (void)videoDidStartLoopAfterFullyViewedForStory:(id)arg1 context:(id)arg2 params:(id)arg3;
//- (void)willAdvanceToNextStory:(id)arg1 friendStories:(id)arg2 lastInteraction:(id)arg3;
//- (void)didLongPressForStory:(id)arg1 friendStories:(id)arg2 isTopSnap:(_Bool)arg3;
- (void)_markStoryAsViewedWithStory:(id)arg1;
//- (void)didChangePanelForStory:(id)arg1 friendStories:(id)arg2 toPanelIndex:(long long)arg3;
//- (void)didPeekToPreviousFriendStories:(id)arg1;
//- (void)didPeekToNextFriendStories:(id)arg1;
//- (void)_clearCurrentStoryStatus;
//- (void)didSwipeUpOnStory:(id)arg1;
//- (void)didTakeScreenshotOnCurrentStory;
//- (void)retryLoadingStory:(id)arg1;
//- (long long)entryEvent;
//- (void)stopShowingFriendStoriesAndCancelRequests:(_Bool)arg1 isShowingStoryInterstitial:(_Bool)arg2;
//- (void)_didPauseInStreamAdOrganizer:(id)arg1;
//- (void)pauseShowingCurrentFriendStoriesWithIsShowingStoryInterstitial:(_Bool)arg1 lastInteraction:(id)arg2;
//- (void)didDismissOptOutInterstitial;
//- (void)_logSubscriptionViewWithContext:(id)arg1 params:(id)arg2 adRequestClientId:(id)arg3 snapIndex:(long long)arg4;
//- (void)_logStoreViewWithContext:(id)arg1 params:(id)arg2 adRequestClientId:(id)arg3 snapIndex:(long long)arg4;
//- (void)_logLongformCameraViewWithContext:(id)arg1 params:(id)arg2 adRequestClientId:(id)arg3 snapIndex:(long long)arg4 lastInteraction:(id)arg5;
//- (void)_logRemoteWebpageViewWithContext:(id)arg1 params:(id)arg2 adRequestClientId:(id)arg3 snapIndex:(long long)arg4;
//- (void)_logLongformVideoViewWithContext:(id)arg1 params:(id)arg2 adRequestClientId:(id)arg3 snapIndex:(long long)arg4;
//- (void)_logLocalWebpageViewWithContext:(id)arg1 params:(id)arg2 adRequestClientId:(id)arg3 snapIndex:(long long)arg4;
//- (void)_stopShowingAdsStory:(id)arg1 context:(id)arg2 params:(id)arg3 lastInteraction:(id)arg4;
//- (void)didSwipeUpOnCardCardForStory:(id)arg1 context:(id)arg2 params:(id)arg3;
//- (void)pauseShowingStory:(id)arg1 context:(id)arg2 params:(id)arg3 lastInteraction:(id)arg4;
//- (void)stopShowingStory:(id)arg1 context:(id)arg2 params:(id)arg3 lastInteraction:(id)arg4;
//- (void)willPageToAnotherStory;
//- (void)skipShowingStory:(id)arg1;
//- (void)startPlayingStory:(id)arg1 lastInteraction:(id)arg2;
//- (void)startPlayingAdStory:(id)arg1 isViewingLongform:(_Bool)arg2 lastInteraction:(id)arg3;
//- (id)_nextFriendStoriesAboutToPlay;
//- (_Bool)_isLastStorySnapInFriendStories:(id)arg1;
//- (void)_logIfCurrentStoryExpired;
//- (void)startShowingLoadedStory:(id)arg1 isViewingLongform:(_Bool)arg2 isStreaming:(_Bool)arg3;
//- (void)startShowingLoadingStory:(id)arg1;
//- (void)didOpenFriendStoriesSnap:(id)arg1;
//- (void)_updateRequestManagerContexts;
//- (void)pauseViewingSession;
//- (void)resumeViewingSession;
//- (void)startViewingSessionIsViewingLongform:(_Bool)arg1;
//- (void)dealloc;
//- (id)initWithFirstStory:(id)arg1 friendStories:(id)arg2 userSession:(id)arg3 operaPageProvider:(id)arg4 friendStoriesCollection:(id)arg5 viewingType:(long long)arg6 storyViewingActionContext:(unsigned long long)arg7 viewLocation:(long long)arg8 autoAdvanceAdsDelegate:(id)arg9 inStreamAdOrganizer:(id)arg10 storyLogger:(id)arg11 usageLogger:(id)arg12 diagnosticsLogger:(id)arg13 operaLongformLogger:(id)arg14 storyViewStopwatch:(id)arg15 snapViewStopwatch:(id)arg16 attachmentViewStopwatch:(id)arg17 requestManager:(id)arg18 storiesViewingHandler:(id)arg19 isInStoryPlaylistMode:(_Bool)arg20 didEnterFromInterstitial:(_Bool)arg21 storiesViewingSession:(id)arg22;
//- (id)initWithFirstStory:(id)arg1 friendStories:(id)arg2 userSession:(id)arg3 operaPageProvider:(id)arg4 friendStoriesCollection:(id)arg5 viewingType:(long long)arg6 storyViewingActionContext:(unsigned long long)arg7 viewLocation:(long long)arg8 autoAdvanceAdsDelegate:(id)arg9 storiesViewingHandler:(id)arg10 isInStoryPlaylistMode:(_Bool)arg11 didEnterFromInterstitial:(_Bool)arg12 storiesViewingSession:(id)arg13;

@end

