//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2017 17:44:06).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/Foundation.h>
#import "Snap.h"
#import "SCMediaView.h"
//@class Snap, UIViewController;
//@protocol SCSnapPlayContainer, SCSnapPlayDelegate;

@interface SCSnapPlayController : NSObject
//{
////    UIViewController<SCSnapPlayContainer> *_containerViewController;
//    long long _containerViewType;
//    Snap *_replaySnap;
//    id <SCSnapPlayDelegate> _delegate;
//}

+ (id)shared;
- (SCMediaView *)mediaView;
- (void)hideSnap:(id)arg1;
@property(retain, nonatomic) Snap *replaySnap; // @synthesize replaySnap=_replaySnap;
@property(retain, nonatomic) Snap *visibleSnap;
//@property(nonatomic) __weak id <SCSnapPlayDelegate> delegate; // @synthesize delegate=_delegate;
//- (void).cxx_destruct;
- (id)getPageViewName;
- (void)showReplayCreditUpdatePromptAndReplayAllSnaps:(_Bool)arg1;
- (void)changeSnapOrSnapStackStateWithFirstSnap:(id)arg1 state:(long long)arg2 replayAllSnaps:(_Bool)arg3;
- (void)replaySnapOrSnapStackWithFirstSnap:(id)arg1 hasBeenPaidToReplay:(_Bool)arg2 replayAllSnaps:(_Bool)arg3;
- (id)replayableSnapsForUsername:(id)arg1;
- (void)resetWaitingUpdateCreditsSnaps;
- (void)showFreeReplayAlertView:(id)arg1 replayAllSnaps:(_Bool)arg2;
- (void)promptReplaySnap:(id)arg1 replayAllSnaps:(_Bool)arg2;
- (void)switchToContainerViewController:(id)arg1 delegate:(id)arg2;

- (void)showSnap:(id)arg1;
- (void)showSnap:(id)arg1 pullToDismissFinalCircleFrame:(CGRect)arg2;
@end

