//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/Foundation.h>
#import "SCSingleFriendStoriesViewingSession.h"

//#import "SCOperaPlaylistItemExtraPropertiesProvider-Protocol.h"
//#import "SCOperaSession-Protocol.h"
//#import "SCTimeProfilable-Protocol.h"

//@class CADisplayLink, FriendStories, FriendStoriesCollection, NSArray, NSMutableArray, NSMutableDictionary, NSMutableSet, NSString, SCAttachmentsLogger, SCAudioStitchLogger, SCCheetahStoriesMiniProfileHandler, SCDiscoverSubscriptionSession, SCFeedItemSkipStoryTracker, SCOperaEventListenerAnnouncer, SCOperaPerformanceTrackingPlugin, SCOperaViewController, SCStoriesChatSession, SCStoriesChromeInteractionSession, SCStoriesOperaIconProvider, SCStoriesReportSession, SCStoriesSharingSession, SCStoriesViewersInteractionSession, SCStoryDiagnosticsLogger, SCStoryLogger, SCStoryUsageLogger, SCStoryUserProperties, SCUserSession, Story, User;
//@protocol SCOperaPlaylistItemController, SCOperaSubscribeActionHandler, SCReplyDelegate, SCStoriesAutoAdvanceAdsDelegate, SCStoriesOperaPageProvider, SCStoriesViewingHandler;

@interface SCStoriesViewingSession : NSObject
//<SCTimeProfilable, SCOperaSession, SCOperaPlaylistItemExtraPropertiesProvider>
//{
//    SCUserSession *_userSession;
//    User *_user;
//    SCStoryLogger *_storyLogger;
//    SCStoryUsageLogger *_usageLogger;
//    SCStoryDiagnosticsLogger *_diagnosticsLogger;
//    SCAttachmentsLogger *_attachmentsLogger;
//    SCAudioStitchLogger *_audioStitchLogger;
//    id <SCReplyDelegate> _replyDelegate;
//    FriendStoriesCollection *_friendStoriesCollection;
//    SCStoryUserProperties *_storyUserProperties;
//    unsigned long long _previousSessionsUniqueSnapViewCount;
//    unsigned long long _previousSessionsTotalSnapViewCount;
//    unsigned long long _previousSessionsTotalSnapOpenCount;
//    NSMutableSet *_autoAdvanceViewedKvoUsernames;
//    NSMutableSet *_adStreamInfosForCleanup;
//    Story *_currentStory;
//    SCStoriesViewersInteractionSession *_viewersInteractionSession;
//    SCStoriesChromeInteractionSession *_chromeInteractionSession;
//    SCStoriesChatSession *_chatSession;
//    SCStoriesReportSession *_reportSession;
//    SCStoriesSharingSession *_sharingSession;
//    SCCheetahStoriesMiniProfileHandler *_miniProfileHandler;
//    id <SCOperaSubscribeActionHandler> _subscribeActionHandler;
//    _Bool _currentFriendStoriesHaveStartedPlaying;
//    _Bool _viewingSessionIsStopped;
//    _Bool _isShowingLoadingScreen;
//    _Bool _didEnterBackground;
//    _Bool _shouldShowTapToolTipsForCurrentStory;
//    NSMutableDictionary *_firstStoryDisplayedForUserName;
//    id <SCStoriesAutoAdvanceAdsDelegate> _autoAdvanceAdsDelegate;
//    _Bool _isShowingStoryInterstitial;
//    unsigned long long _entryGroupIndex;
//    CADisplayLink *_foregroundDisplayLink;
//    long long _storyPlayMode;
//    double _playlistStartSetupViewModelsTimeMs;
//    double _playlistSetupViewModelsTimeMs;
//    id <SCStoriesViewingHandler> _storiesViewingHandler;
//    SCOperaPerformanceTrackingPlugin *_performanceTrackingPlugin;
//    SCStoriesOperaIconProvider *_viewersListIconProvider;
//    SCDiscoverSubscriptionSession *_attachmentSubscriptionSession;
//    long long _initialPlaySource;
//    SCFeedItemSkipStoryTracker *_skipStoryTracker;
//    _Bool _isReplayMode;
//    _Bool _isInStoryPlaylistMode;
//    _Bool _isTopSnap;
//    _Bool _isFullyViewed;
//    _Bool _isViewingLongform;
//    long long _viewingType;
//    unsigned long long _storiesViewingContext;
//    long long _sourceViewLocation;
//    long long _viewLocation;
//    unsigned long long _viewLocationPosition;
//    unsigned long long _liveStoriesCount;
//    long long _storySessionId;
//    long long _tileSizeType;
//    unsigned long long _entryReason;
//    unsigned long long _defaultStoryViewingActionContext;
//    unsigned long long _totalViewedStoriesCount;
//    NSMutableArray *_currentFriendStoriesViewingSessions;
//    NSArray *_selectedFriendNamesInPlaylist;
//    NSArray *_friendNamesInRecentUpdate;
//    unsigned long long _loadingScreenCount;
//    NSString *_sortOrderId;
//    long long _playSource;
//    NSString *_collectionId;
//    long long _collectionPos;
//    long long _collectionType;
//    SCOperaEventListenerAnnouncer *_eventAnnouncer;
//    id <SCStoriesOperaPageProvider> _operaPageProvider;
//    FriendStories *_previousFriendStoriesDisplayed;
//    SCOperaViewController *_operaVC;
//    unsigned long long _initialFriendsPlayListCount;
//    id <SCOperaPlaylistItemController> _playlistItemController;
//}
//
//+ (id)announcerIdentifier;
//+ (int)context;
//@property(nonatomic) __weak id <SCOperaPlaylistItemController> playlistItemController; // @synthesize playlistItemController=_playlistItemController;
//@property(readonly, nonatomic) unsigned long long initialFriendsPlayListCount; // @synthesize initialFriendsPlayListCount=_initialFriendsPlayListCount;
//@property(nonatomic) __weak SCOperaViewController *operaVC; // @synthesize operaVC=_operaVC;
//@property(readonly, nonatomic) FriendStories *previousFriendStoriesDisplayed; // @synthesize previousFriendStoriesDisplayed=_previousFriendStoriesDisplayed;
//@property(nonatomic) __weak id <SCStoriesOperaPageProvider> operaPageProvider; // @synthesize operaPageProvider=_operaPageProvider;
//@property(retain, nonatomic) SCOperaEventListenerAnnouncer *eventAnnouncer; // @synthesize eventAnnouncer=_eventAnnouncer;
//@property(readonly, nonatomic) long long collectionType; // @synthesize collectionType=_collectionType;
//@property(readonly, nonatomic) long long collectionPos; // @synthesize collectionPos=_collectionPos;
//@property(readonly, copy, nonatomic) NSString *collectionId; // @synthesize collectionId=_collectionId;
//@property(readonly, nonatomic) long long playSource; // @synthesize playSource=_playSource;
//@property(readonly, nonatomic) _Bool isViewingLongform; // @synthesize isViewingLongform=_isViewingLongform;
//@property(readonly, copy, nonatomic) NSString *sortOrderId; // @synthesize sortOrderId=_sortOrderId;
//@property(readonly, nonatomic) _Bool isFullyViewed; // @synthesize isFullyViewed=_isFullyViewed;
//@property(readonly, nonatomic) unsigned long long loadingScreenCount; // @synthesize loadingScreenCount=_loadingScreenCount;
//@property(readonly, nonatomic) _Bool isTopSnap; // @synthesize isTopSnap=_isTopSnap;
//@property(readonly, copy, nonatomic) NSArray *friendNamesInRecentUpdate; // @synthesize friendNamesInRecentUpdate=_friendNamesInRecentUpdate;
//@property(readonly, copy, nonatomic) NSArray *selectedFriendNamesInPlaylist; // @synthesize selectedFriendNamesInPlaylist=_selectedFriendNamesInPlaylist;
//@property(readonly, nonatomic) _Bool isInStoryPlaylistMode; // @synthesize isInStoryPlaylistMode=_isInStoryPlaylistMode;
//@property(readonly, nonatomic) NSMutableArray *currentFriendStoriesViewingSessions; // @synthesize currentFriendStoriesViewingSessions=_currentFriendStoriesViewingSessions;
//@property(readonly, nonatomic) unsigned long long totalViewedStoriesCount; // @synthesize totalViewedStoriesCount=_totalViewedStoriesCount;
//@property(nonatomic) unsigned long long defaultStoryViewingActionContext; // @synthesize defaultStoryViewingActionContext=_defaultStoryViewingActionContext;
//@property(nonatomic) unsigned long long entryReason; // @synthesize entryReason=_entryReason;
//@property(nonatomic) long long tileSizeType; // @synthesize tileSizeType=_tileSizeType;
//@property(nonatomic) long long storySessionId; // @synthesize storySessionId=_storySessionId;
//@property(nonatomic) unsigned long long liveStoriesCount; // @synthesize liveStoriesCount=_liveStoriesCount;
//@property(nonatomic) unsigned long long viewLocationPosition; // @synthesize viewLocationPosition=_viewLocationPosition;
//@property(nonatomic) long long viewLocation; // @synthesize viewLocation=_viewLocation;
//@property(nonatomic) long long sourceViewLocation; // @synthesize sourceViewLocation=_sourceViewLocation;
//@property(nonatomic) unsigned long long storiesViewingContext; // @synthesize storiesViewingContext=_storiesViewingContext;
//@property(nonatomic) long long viewingType; // @synthesize viewingType=_viewingType;
//@property(readonly, nonatomic) _Bool isReplayMode; // @synthesize isReplayMode=_isReplayMode;
//- (void).cxx_destruct;
//- (_Bool)subscriptionAttachmentIsSubscribed;
//- (_Bool)shouldUseExtendedResetToCamera;
//- (id)firstDisplayedStoryForFriendStories:(id)arg1;
//- (void)extraPropertiesForDataModel:(id)arg1 item:(id)arg2 completion:(CDUnknownBlockType)arg3;
//- (id)initWithUserSession:(id)arg1 user:(id)arg2 replyDelegate:(id)arg3 friendStoriesCollection:(id)arg4 storyUserProperties:(id)arg5 skipStoryTracker:(id)arg6 storyPlayMode:(long long)arg7 selectedFriendKvoNameList:(id)arg8 recentUpdateFriendKvoNameList:(id)arg9 viewLocation:(long long)arg10 sortOrderId:(id)arg11 viewingType:(long long)arg12 storiesViewingContext:(unsigned long long)arg13 viewLocationPosition:(unsigned long long)arg14 tileSizeType:(long long)arg15 collectionId:(id)arg16 collectionPos:(long long)arg17 collectionType:(long long)arg18 storyViewingActionContext:(unsigned long long)arg19 viewersListIconProvider:(id)arg20 playSource:(long long)arg21 miniProfileHandler:(id)arg22;
//- (void)cleanUpAdsForFriendStoriesViewingSessions;
//- (id)_friendKVONameArrayToFriendNameArray:(id)arg1;
//- (long long)_playSourceUponOpenOpera;
//- (void)_logPlaybackPerformance:(id)arg1 story:(id)arg2 isStreaming:(_Bool)arg3 params:(id)arg4;
//- (unsigned long long)uniqueViewedAdSnapsCount;
//- (unsigned long long)totalViewedAdSnapsCount;
//- (unsigned long long)totalViewedAdStoriesCount;
//- (unsigned long long)uniqueViewedAdStoriesCount;
//- (unsigned long long)totalOpenedSnapsCount;
//- (unsigned long long)totalViewedSnapsCount;
//- (unsigned long long)uniqueViewedSnapsCount;
//- (unsigned long long)uniqueViewedStoriesCount;
//- (unsigned long long)finishWaitingReason;
//- (id)lastInteraction;
//- (long long)exitReason;
//- (void)viewWillEnterBackground;
//- (void)userDidScreenRecord;
//- (void)userDidTakeScreenshot;
//- (void)_removeFriendStoriesViewingSession:(id)arg1;
//- (void)_updateCurrentFriendStoriesViewingSessionsWithEvent:(id)arg1 context:(id)arg2;
//- (unsigned long long)indexOfStoryRelativeToInitialStory:(id)arg1;
//- (unsigned long long)currentFriendStoriesRelativeIndex;
//- (unsigned long long)currentFriendStoriesAbsoluteIndex;
//- (unsigned long long)currentFriendStoriesViewingSessionLevelIndex;
- (SCSingleFriendStoriesViewingSession *)currentFriendStoriesViewingSession;
//- (void)_setupSubscriptionSession;
//- (void)_setupSharingSession;
//- (void)_setupReportSession;
//- (void)_setupChatSession;
//- (void)_setupChromeInteractionSession;
//- (void)_setupViewersInteractionSession;
//- (void)_didStartPlayingAdStory:(id)arg1 isViewingLongform:(_Bool)arg2 lastInteraction:(id)arg3;
//- (void)_didStartPlayingStory:(id)arg1 friendStories:(id)arg2;
//- (_Bool)hasSessionEnded;
//- (void)_editionDoesDisplaySinceForegroundedApp;
//- (void)viewDidEnterBackground;
//- (void)viewWillEnterForeground;
//- (void)operaViewDidSendEvent:(id)arg1 context:(id)arg2 params:(id)arg3;
//- (id)registeredEventsForOperaSession;
//- (id)_extraToolTipsPropertiesForStories:(id)arg1;
//- (id)extraPropertiesForStory:(id)arg1;
//- (void)_markCheetahSwipeLeftInterstitialCompleted;
//- (_Bool)_shouldShowCheetahSwipeLeftInterstitial:(id)arg1;
//- (void)_incrementTotalViewedStoriesCount:(id)arg1;
//- (_Bool)_isOnStoriesPage;
//- (void)_logEndViewMedia;
//- (void)_updateSkipStoryTrackerForPreviousFriendStories:(id)arg1 wasShowingStoryInterstitial:(_Bool)arg2;
//- (void)_logStoryStoryViewSession;
//- (void)_pauseSession;
//- (void)stopSession;
//- (void)_updateFirstPagePropertyWithTooltipIfNecessary;
//- (void)startSession;
//- (void)didUpdateFriendsPlaylistCount:(unsigned long long)arg1;
//- (void)dealloc;
//- (id)initWithEventAnnouncer:(id)arg1 userSession:(id)arg2 user:(id)arg3 operaPageProvider:(id)arg4 operaViewController:(id)arg5 replyDelegate:(id)arg6 storiesViewingHandler:(id)arg7 friendStoriesCollection:(id)arg8 storyLogger:(id)arg9 usageLogger:(id)arg10 diagnosticsLogger:(id)arg11 viewersInteractionSession:(id)arg12 chromeInteractionSession:(id)arg13 chatSession:(id)arg14 reportSession:(id)arg15 sharingSession:(id)arg16 autoAdvanceAdsDelegate:(id)arg17 storyUserProperties:(id)arg18 skipStoryTracker:(id)arg19 isReplayMode:(_Bool)arg20 isInStoryPlaylistMode:(_Bool)arg21 selectedFriendKvoNameList:(id)arg22 recentUpdateFriendKvoNameList:(id)arg23 viewLocation:(long long)arg24 sortOrderId:(id)arg25 collectionId:(id)arg26 collectionPos:(long long)arg27 collectionType:(long long)arg28 performanceTrackingPlugin:(id)arg29 viewersListIconProvider:(id)arg30 playSource:(long long)arg31;
//- (id)initWithEventAnnouncer:(id)arg1 userSession:(id)arg2 user:(id)arg3 operaPageProvider:(id)arg4 operaViewController:(id)arg5 replyDelegate:(id)arg6 storiesViewingHandler:(id)arg7 friendStoriesCollection:(id)arg8 storyUserProperties:(id)arg9 skipStoryTracker:(id)arg10 isReplayMode:(_Bool)arg11 isInStoryPlaylistMode:(_Bool)arg12 selectedFriendKvoNameList:(id)arg13 recentUpdateFriendKvoNameList:(id)arg14 viewLocation:(long long)arg15 sortOrderId:(id)arg16 collectionId:(id)arg17 collectionPos:(long long)arg18 collectionType:(long long)arg19 performanceTrackingPlugin:(id)arg20 viewersListIconProvider:(id)arg21 playSource:(long long)arg22;
//
//// Remaining properties
//@property(readonly, copy) NSString *debugDescription;
//@property(readonly, copy) NSString *description;
//@property(readonly) unsigned long long hash;
//@property(readonly) Class superclass;

@end

