//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCLeftSwipableViewController.h"

//@class FBKVOController, NSArray, NSString, SCAuthenticatedPhoneManager, SCHeader, SCPotentiallyEligibleCashUserFlow, SCReauthenticationManager, SCSettingHeaderPromptView, SCSettingsEmailPhonePromptExperimentContext, SCUserSession, UILabel, UILongPressGestureRecognizer, UITableView;
//@protocol NavigationDelegate, SCCanceling, SCLagunaPairingDelegate, SCSettingsUserActionDelegate, SCStartChatDelegate;

@interface SettingsViewController : SCLeftSwipableViewController
//<SCHeaderDataSource, SCHeaderDelegate, SCPotentiallyEligibleFlowDelegate, UINavigationControllerDelegate, SCShareUsernameControllerDelegate, SCSettingHeaderPromptViewDelegate, UITableViewDataSource, UITableViewDelegate>
//{
//    SCUserSession *_userSession;
//    NSArray *_settingsAccountOptions;
//    NSArray *_settingsWhoCanOptions;
//    SCReauthenticationManager *_reauthenticationManager;
//    SCAuthenticatedPhoneManager *_authenticatedPhoneManager;
//    SCSettingsEmailPhonePromptExperimentContext *_settingsEmailPhonePromptExperimentContext;
//    id <SCSettingsUserActionDelegate> _userActionDelegate;
//    id <SCLagunaPairingDelegate> _pairingDelegate;
//    id <SCStartChatDelegate> _startChatDelegate;
//    id <SCCanceling> _managedBusinessProfilesObserver;
//    NSArray *_managedBusinessProfiles;
//    _Bool _hasPendingBusinessInvites;
//    long long _exitType;
//    id <NavigationDelegate> _navigationDelegate;
//    SCPotentiallyEligibleCashUserFlow *_potentiallyEligibleFlow;
//    UILongPressGestureRecognizer *_press;
//    SCHeader *_header;
//    UITableView *_tableView;
//    UILabel *_madeLabel;
//    FBKVOController *_KVOController;
//    SCSettingHeaderPromptView *_headerPromptView;
//}
//
//@property(retain, nonatomic) SCSettingHeaderPromptView *headerPromptView; // @synthesize headerPromptView=_headerPromptView;
//@property(retain, nonatomic) FBKVOController *KVOController; // @synthesize KVOController=_KVOController;
//@property(retain, nonatomic) UILabel *madeLabel; // @synthesize madeLabel=_madeLabel;
//@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
//@property(retain, nonatomic) SCHeader *header; // @synthesize header=_header;
//@property(retain, nonatomic) UILongPressGestureRecognizer *press; // @synthesize press=_press;
//@property(retain, nonatomic) SCPotentiallyEligibleCashUserFlow *potentiallyEligibleFlow; // @synthesize potentiallyEligibleFlow=_potentiallyEligibleFlow;
//@property(nonatomic) __weak id <NavigationDelegate> navigationDelegate; // @synthesize navigationDelegate=_navigationDelegate;
//- (void).cxx_destruct;
//- (void)settingHeaderPromptViewDidTapButton:(id)arg1;
//- (void)presentActivityViewController:(id)arg1 shareUsernameController:(id)arg2;
//- (long long)_businessOptionForIndexPath:(id)arg1 adjustedRow:(long long *)arg2;
//- (_Bool)shouldShowSection:(long long)arg1;
//- (void)_didSelectUsernameCell;
//- (id)_officialStoryUsernames;
//- (id)_pageNameForPageView;
//- (id)_getEmailPhonePromptText;
//- (id)_getEmailPhonePromptTitle;
//- (_Bool)_shouldShowPrompt;
//- (long long)getSettingsWhoCanOptionForRow:(long long)arg1;
//- (_Bool)showShakeToReportSettings;
//- (long long)getSettingsServicesTypeForRow:(long long)arg1;
//- (_Bool)showOfficialStorySettings;
//- (id)navigationController:(id)arg1 animationControllerForOperation:(long long)arg2 fromViewController:(id)arg3 toViewController:(id)arg4;
//- (void)processNotification:(id)arg1;
//- (_Bool)shouldPopToRootViewControllerLater;
//- (_Bool)shouldPopToRootViewController;
//- (void)leftSwipeSucceed;
//- (_Bool)inValidView:(id)arg1;
//- (void)flowSuccessfullyCompleted;
//- (void)presentNotificationSettings;
//- (void)presentBlocked;
//- (void)presentClearDataVC;
//- (void)_clearRecentlyUsedStickerTags;
//- (void)_clearStickerSearch;
//- (void)presentClearConversations;
//- (void)logPresentPreview;
//- (void)presentBusinessSupport;
//- (void)presentBusinessProfileInvitations;
//- (void)presentManagedBusinessProfile:(id)arg1;
//- (void)presentActivateBusinessProfile;
//- (void)_pushSerengetiViewControllerWithLink:(id)arg1;
//- (void)presentOfficialStorySettings;
//- (void)presentMapSettings;
//- (void)presentShazamServices;
//- (void)presentShakeToReportSettings;
//- (void)presentAdditionalServices;
//- (void)_presentLogoutAlert;
//- (void)_presentGalleryBackupWithBackupNow:(_Bool)arg1;
//- (void)_presentGalleryLogoutAlertWithPendingSnapsCount:(unsigned long long)arg1 pendingStickersCount:(unsigned long long)arg2;
//- (void)presentLogout;
//- (void)presentSupportPage;
//- (void)presentOtherLegal;
//- (void)presentTermsOfUse;
//- (void)presentPrivacyPolicy;
//- (void)presentQuickAddPrivacySettings;
//- (void)presentViewMyStoriesSettings;
//- (void)presentSendMeNotificationsSettings;
//- (void)presentSendMeSnapsSettings;
//- (void)presentPaymentsSettingsV2;
//- (void)presentSnapAdsPortalSettings;
//- (void)presentLagunaSettings;
//- (void)presentGallerySettings;
//- (void)presentCashSettingsVC;
//- (void)presentTwoFASettings;
//- (void)presentPasswordSettings;
//- (void)presentSnapConnectSettings;
//- (void)_presentBitmojiSettings;
//- (void)_presentSnapStore;
//- (void)_presentSnapcodeSettings;
//- (void)presentDisplayOnDemandGeofilters;
//- (void)presentEmailSettings;
//- (void)presentMobileSettings;
//- (void)presentBirthdaySettings;
//- (void)presentDisplayNameSettings;
//- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
//- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
//- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
//- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
//- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
//- (void)_updateCacheSize;
//- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
//- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
//- (long long)numberOfSectionsInTableView:(id)arg1;
//- (void)reloadTableOnMainThread;
//- (void)reloadTableWithNewCells;
//- (void)addMonetizationLoadedObservers;
//- (void)addPrivacyObservers;
//- (void)addEmailObservers;
//- (void)addSettingsObservers;
//- (void)leftButtonPressed;
//- (id)imageForRightButtonInState:(unsigned long long)arg1;
//- (id)imageForLeftButtonInState:(unsigned long long)arg1;
//- (id)textColorForHeader:(id)arg1;
//- (id)titleForHeader:(id)arg1;
//- (id)backgroundColorForHeader;
//- (unsigned long long)supportedInterfaceOrientations;
//- (void)didMoveToParentViewController:(id)arg1;
//- (void)viewDidLayoutSubviews;
//- (void)viewDidDisappear:(_Bool)arg1;
//- (void)viewDidAppear:(_Bool)arg1;
//- (void)viewWillDisappear:(_Bool)arg1;
//- (void)viewWillAppear:(_Bool)arg1;
//- (void)didBecomeActive;
//- (void)viewDidLoad;
//- (void)dealloc;
//- (void)initWhoCanOptions;
//- (void)initSettingsAccountOptions;
//- (void)initPromptHeader;
//- (void)initHeader;
//- (void)loadView;
//- (id)initWithUserSession:(id)arg1 userActionDelegate:(id)arg2 navigationDelegate:(id)arg3 pairingDelegate:(id)arg4 startChatDelegate:(id)arg5;
//- (id)getPageViewName;
//
//// Remaining properties
//@property(readonly, copy) NSString *debugDescription;
//@property(readonly, copy) NSString *description;
//@property(readonly) unsigned long long hash;
//@property(readonly) Class superclass;

@end

